### ISSUE TITLE
Issue with the Villager Hats mod

### ISSUE THREAD

**Issue by Swordee** [tr7zw/FirstPersonModel#1]
The first person render is quite buggy with the Villager Hats mod, I was hoping this could be fixed as it's a really cool mod, along with yours. 

![image](https://user-images.githubusercontent.com/52900125/63039194-658bc800-be88-11e9-8b56-be73612fef46.png)

**Comment by tr7zw** [comment]
Confirmed fixed with the newest way of hiding stuff that gets added to the head.
