### ISSUE TITLE
Food bar turns into enchantment texture or random blocks.

### ISSUE THREAD

**Issue by erlandyt** [tr7zw/FirstPersonModel#104]
The title explains everything.
I am using the 2.0.0 beta2 version in forge

**Comment by tr7zw** [comment]
Eh that sounds like some other mod majorly screwing up. Can you post your mod list?

**Comment by erlandyt** [comment]
[normal.zip](https://github.com/tr7zw/FirstPersonModel/files/6097129/normal.zip)
Here

**Comment by tr7zw** [comment]
Try to update mods like optifine. That is still a G4 preview version, and G7 non preview is already out.
