### ISSUE TITLE
Enabling Paperdoll causes visual bug with armor/hunger bars

### ISSUE THREAD

**Issue by blcklghtngvg** [tr7zw/FirstPersonModel#107]
Title.

I'm using Forge 36.0.55, and it happens on 36.0.42 as well. I haven't tried any other versions. Bug is reproducible with the only loaded mods being:
- FirstpersonModel 2.0.0-beta2
- TRansliterationLib 1.0.2

Paperdoll enabled:
![enabled](https://user-images.githubusercontent.com/58446743/111050779-3fd3f580-8414-11eb-8a8e-53a6f3c566c4.png)

Paperdoll disabled:
![disabled](https://user-images.githubusercontent.com/58446743/111050783-4498a980-8414-11eb-80df-43be1a96104b.png)

I'm very confused about what could be causing this. Few other users seem to be reporting this behavior.

**Comment by tr7zw** [comment]
I only know about #104 and there it's likely a very outdated optifine. Outside of that I haven't seen/heard of this?

**Comment by tr7zw** [comment]
Ok but I was able to reproduce it, so something broke I guess?  I'll look into it.
