### ISSUE TITLE
1.16.5 Bug with mod MrCrayfish's Gun Mod

### ISSUE THREAD

**Issue by Senyum** [tr7zw/FirstPersonModel#122]
Hi, i get visual bug on version mod FirstPersonMod-2.0.0-SNAPSHOT.jar and TRansliterationLib-1.0.4.jar. When i use weapon i get this effect 
![Screenshot_3](https://user-images.githubusercontent.com/36424845/114273246-f3370680-9a21-11eb-9779-4d6d0d7d14a9.png)

**Comment by tr7zw** [comment]
Eh update the mod. Got fixed in #98
