### ISSUE TITLE
Player Head skin doesn't work in Forge version

### ISSUE THREAD

**Issue by ohnecksThing** [tr7zw/FirstPersonModel#124]
The title pretty much explains everything, First I tried the mod on Fabric, and everything worked fine (excluding the experimental features which are currently unfinished anyways), and "Player Head skin", when turned on, worked as intended: you wear a player head and the skin of it applies to you. But when I tried that on Forge, for some reason... that just does not work, at all. I tried messing with options, turning "Player Head skin" off and on again, changing others, but nothing changes, you just wear a head and... that's it, you just wear a head, nothing else, whatever if the option is on or off. Probably not intended, but I assume that might just be just a little oversight exactly on Forge, not quite sure...

**Comment by tr7zw** [comment]
This has been removed from the mod. https://github.com/tr7zw/DisguiseHeads
