### ISSUE TITLE
Visual Issue with emissive armor

### ISSUE THREAD

**Issue by Answordy** [tr7zw/FirstPersonModel#127]
While normal helmets aren't rendered in first person, emissive ones are, and they are blocking vision. 
In my case, I have a diamond and a gold helmet with emissive textures (attached the pictures) and they are kinda "buggy" (I won't say it's a bug, but it's ofc annoying)
Other helmets are working, they aren't rendered in first person.

My best guess is that it's because these emissive textures are additional layers on top of the original layers. And while the mod isn't rendering the normal armor layer, it renders the emissive one since it's a rare case, not a vanilla feature, but optifine. 
[Also as far as I know emissive textures have different names, like... gold_layer_1_(extension) the extension can be anything tho it's usually 'e' but since it's not uniform.. it may be a problem?.. or idk.. can this issue be fixed?]
![2021-04-19_00 20 23](https://user-images.githubusercontent.com/82783515/115163814-8c61bf00-a0ab-11eb-8261-7d3ff8a25c53.png)
![2021-04-19_00 20 48](https://user-images.githubusercontent.com/82783515/115163822-9683bd80-a0ab-11eb-9c2b-e71b8b88f054.png)

**Comment by tr7zw** [comment]
I am aware of that issue, but I don't have the slightest clue how to fix that thanks to optifines locked down source. So if anyone has a lead on how to tell optifine not to render that stuff be my guest.

**Comment by AlienXtream** [comment]
to suggest a temp (end user) workaround. get the cosmetic armour reworked (or something like that) mod and you can actually set it to not render the selected armour slot.

**Comment by MarkinhosMLP** [comment]
UP! "alienxtream"s idea is awesome, it would be nice if you could disable the helmet render when in 1st person then

**Comment by tr7zw** [comment]
Fixed.
