### ISSUE TITLE
[suggestion/request] Camera-body yaw locking.

### ISSUE THREAD

**Issue by AlienXtream** [tr7zw/FirstPersonModel#163]
the only issue i have (design wise, not sure about bugs) is the way the body rotates with the camera. i know its how it works in 3rd person but in first person its a bit weird. an option to lock the body rotation to the camera's yaw in first person (and not riding an entity) would be nice. that aside this is a really nice mod and adds SO much more to the game without actually changing anything functionality wise

**Comment by tr7zw** [comment]
This was added a long time ago in Not Enough Animations.
