### ISSUE TITLE
[1.16.5 Forge] The trident is held backwards

### ISSUE THREAD

**Issue by V972** [tr7zw/FirstPersonModel#165]
Forge 36.1.15
Not Enough Animations 1.2.4
TRansliterationLib 1.0.4
_Shoulder Surfing 2.0.6 (If needed)_

The trident is helf backwards (but only when the player is charging it to throw, just idle holding it in the hand is normal)

![image](https://user-images.githubusercontent.com/45125685/121499004-a487f780-c9e5-11eb-925a-c09feaaba8c6.png)

**Comment by tr7zw** [comment]
Probably was caused by some odd mod combination, hasn't been observed since.
