### ISSUE TITLE
1.16.5 Bug when player sit

### ISSUE THREAD

**Issue by Senyum** [tr7zw/FirstPersonModel#174]
Hi, i have visual bug in latest mod version.

When the character sits down, his headless body is visible. Observed in all mods in which you can sit on furniture. As an example
Furniture Mod 7.0.0pre22

![Screenshot_3](https://user-images.githubusercontent.com/36424845/122674943-eda72b00-d1df-11eb-86f4-c4720a2d6261.png)

**Comment by tr7zw** [comment]
Duplicate #77
