### ISSUE TITLE
Having a parrot on your shoulder in first person with shaders on crashes

### ISSUE THREAD

**Issue by eDexiam** [tr7zw/FirstPersonModel#183]
[crash-2021-07-03_16.53.53-client.txt](https://github.com/tr7zw/FirstPersonModel/files/6758606/crash-2021-07-03_16.53.53-client.txt)

If you want more details let me know

**Comment by tr7zw** [comment]
Huh I can replicate it. My guess is that it's an optifine oversight, missing a null check. I'll ask there rather they have a clue.

**Comment by eDexiam** [comment]
Did you get anything out of them?

**Comment by tr7zw** [comment]
Only found more issues with optifine like random glowing with some shaders while in first person or apparently the own shadow being a bit of a mess. So far not much I can do about it other than waiting for them to fix that I guess, or using Iris instead.

**Comment by eDexiam** [comment]
I've never really encountered that, there might be way to check if shaders are being used and skip rendering the parrot, I don't know if it could fix it but it's an idea nevertheless

**Comment by tr7zw** [comment]
I mean I don't have anything special on my end in regards to the parrot. Ofc I could try to hotfix it by adding something that tries to detect shader and then tries to disable the parrot. But I guess it's better to keep it this way and not hide the bugs of optifine(in this case the missing null check).

**Comment by ThinkWithPbody** [comment]
I came to see if anyone else had reported the glowing on some handheld items when using optifine shaders with forge for 1.18.1. Tried putting the parrot on and crashed as well. It's been more than a year now, do you now see a solution to this apart from avoiding optifine?

**Comment by tr7zw** [comment]
Avoiding optifine(tbh this is one of the least reasons you should avoid it, especially in 1.18). But yea the error is inside optifine and not much I can do other than reporting it and recommending Sodium+Iris instead.

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/e51ecb5a-d4b3-4218-85f9-3695b2eef938)
I guess good news, optifine fixed it at least in 1.19.2+
