### ISSUE TITLE
[Incompatibility issues] Not compatible with Carry On mod

### ISSUE THREAD

**Issue by Charlobo** [tr7zw/FirstPersonModel#193]
Currently, when using this mod Carry on (https://www.curseforge.com/minecraft/mc-mods/carry-on). After lifting an entity or block, the arm disappears and the object that carries cannot be seen.  
![2021-07-19_12 12 57](https://user-images.githubusercontent.com/51576635/126101827-6956d241-1839-49f2-8e88-fa05711a88a3.png)
![2021-07-19_12 12 58](https://user-images.githubusercontent.com/51576635/126101830-09479251-3d1f-45ce-ac66-1368b1abcc3a.png)
![2021-07-19_12 13 02](https://user-images.githubusercontent.com/51576635/126101831-5d239c01-4d9c-40ff-8e33-3890712b5d07.png)

**Comment by tr7zw** [comment]
Duplicate #160
