### ISSUE TITLE
1.17.1: 3D Skin Layer Feature doesn't align correctly

### ISSUE THREAD

**Issue by thatoneguydan** [tr7zw/FirstPersonModel#205]
When turning on 3D skin, the pixels seem misaligned on the player model. I know cosmetics are a known issue, not sure if this feature falls under the umbrella of cosmetics. Tested with Alex model, haven't tried Steve model.

**Comment by tr7zw** [comment]
It does fall under the the same thing, since the general custom cube rendering is broken. I'll probably remove all cosmetic stuff from the mod and move it over into its own thing.

**Comment by tr7zw** [comment]
Got moved into its own mod. https://github.com/tr7zw/3d-Skin-Layers
