### ISSUE TITLE
Third-person map shows with "Vanilla hands" option enabled

### ISSUE THREAD

**Issue by Samarai** [tr7zw/FirstPersonModel#229]
[Imgur album displaying the problem](https://imgur.com/a/uKIgQGP)
Image 1: Looking down (and to the side) at a map with "vanilla hands" turned on. The player's third-person arms are hidden as expected, and other items don't render twice as intended, but maps specifically render twice. 

Image 2: Looking down at a map with vanilla hands disabled. The map only renders once as intended.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/NotEnoughAnimations/issues/17

**Comment by Samarai** [comment]
> [tr7zw/NotEnoughAnimations#17](https://github.com/tr7zw/NotEnoughAnimations/issues/17)

Oops, thanks for responding, and sorry for reporting a known issue!

**Comment by tr7zw** [comment]
Yea the comment was more about the fact that it's technically not a bug of FirstPersonModel and to link the two issues.
