### ISSUE TITLE
Antique Atlas Compatability

### ISSUE THREAD

**Issue by KxmischesDomi** [tr7zw/FirstPersonModel#231]
The Antique Atlas book is not proberly showing in hand when the FirstPersonModel is activated.

Deactivated:
![](https://user-images.githubusercontent.com/67184131/132555300-b13abdce-b462-4c21-9a4d-de6a413b12f5.png)

Activated:
![image](https://user-images.githubusercontent.com/67184131/132555491-a93390f8-4552-46e7-998f-f6b83bb6e2bd.png)

**Comment by tr7zw** [comment]
https://github.com/tr7zw/NotEnoughAnimations/issues/13
