### ISSUE TITLE
[Feature] Add an option for min rotation of head to move the body

### ISSUE THREAD

**Issue by alexmozaidze** [tr7zw/FirstPersonModel#234]
Every time I want to look down from the top of the ravine, I can't see anything because my body won't move out of the way until I attack, which is annoying (especially with shields). It would be nice if there was an option to set minimum rotation for the head in order to rotate the body (like rotation locking with shields, but more configurable and not only for shields).

**Comment by tr7zw** [comment]
I can add the locking like on shields, for changing the vanilla body turn rate compared to the head I'll have to look into how that works. As an fyi: You can toggle the mod with F6 and change the model position relative to the camera in the settings to move the body further back.

**Comment by tr7zw** [comment]
This has been added to Not enough Animations.
