### ISSUE TITLE
1.16.5 server-side error

### ISSUE THREAD

**Issue by Raipus** [tr7zw/FirstPersonModel#236]
Hello. Today, all the players on the server found the same error. 

We don't see any changes in other players.

I attach for you a screenshot with the error that it gives when trying to upload changes to the server.

![image](https://user-images.githubusercontent.com/92184466/136620712-77749cbb-2151-4051-9baf-4e5fcca94197.png)

**Comment by tr7zw** [comment]
Hm looks like the root restarted and the sync server was/is not yet migrated into docker with an autostart. But it's started and working again.
