### ISSUE TITLE
1.16.5 Fabric Game Crash (Mac)

### ISSUE THREAD

**Issue by GhostIsBeHere** [tr7zw/FirstPersonModel#240]
Game will crash on startup when using Versions 2.0.1 and 2.0.0.
[Log](https://paste.atlauncher.com/view/852f384c-9401-4035-83b8-a6f0a18d9806)

**Comment by tr7zw** [comment]
Huh that crash report kinda doesn't match up with the code? Give it a try with the build from here https://github.com/tr7zw/FirstPersonModel/actions/runs/1255207386

**Comment by Unconventional10** [comment]
That seems to have worked! Thanks!

**Comment by tr7zw** [comment]
Thats odd, since that build should be more or less the same 🤔 Guess I'll do a new release on curse soon.
