### ISSUE TITLE
Incompatibility with Big Pony

### ISSUE THREAD

**Issue by autumnblazey** [tr7zw/FirstPersonModel#244]
Hello! When I have this mod and the [Big Pony mod](https://github.com/MineLittlePony/BigPony) installed, the game crashes on launch. I believe it's something to do with Big Pony modifying the model size and hitbox conflicting with something that this mod does.

Here is a crash log with only this mod, Big Pony, and Fabric API: [crash-2021-12-16_12.07.12-client.txt](https://github.com/tr7zw/FirstPersonModel/files/7730129/crash-2021-12-16_12.07.12-client.txt)

Issue on Big Pony repo: minelittlepony/bigpony#12

**Comment by tr7zw** [comment]
They both have a Redirect for the shadow position logic(from what I can tell), making them incompatible with each other. Don't think there is a straightforward way to fix this?

**Comment by Sollace** [comment]
This has been fixed from my end in https://github.com/MineLittlePony/BigPony/issues/12. Sorry about that!

**Comment by tr7zw** [comment]
Ah ok, then this can stay closed :D
