### ISSUE TITLE
Seus PTGI HRR 2 player shadows are broken when this mod is installed (1.18 IRISODIUM)

### ISSUE THREAD

**Issue by just-chubbyfoxx** [tr7zw/FirstPersonModel#248]
There isnt any clear answer to why this happens, but what I see is a giant shadow under all players. Doesnt apply to entities, just players. Logs doesnt seem to suggest anything wrong.

**Comment by tr7zw** [comment]
Could you add an image to the issue, and could it be the vanilla shadow?

**Comment by just-chubbyfoxx** [comment]
It is specifically said 'Seus PTGI' shadows. It is a raytracing shader. Ill have the image for you in a couple of hours

**Comment by tr7zw** [comment]
Yea I know what Seus is, but with other shaders like Complementary on Iris there is no issue. So the only thing I could imagine is that it renders the vanilla shadow while the shader is active? Otherwise, I need more info.

**Comment by just-chubbyfoxx** [comment]
![Minecraft_ 1 18 1 2_8_2022 5_25_17 PM](https://user-images.githubusercontent.com/83988319/153092735-8fc22aed-2f92-49e8-aad2-e4a344e2ba36.png)

**Comment by just-chubbyfoxx** [comment]
Sorry I was so late, I was busy doing things irl.

**Comment by tr7zw** [comment]
Yea that looks like potentially the vanilla shadow, try updating iris and sodium. Could also be a flaw with Seus, since Complementary doesn't have this issue.

**Comment by just-chubbyfoxx** [comment]
It seems to be only Seus that has this issue, and I am on the latest IRISODIUM (1.2.0). This is only an issue when this mod is installed, maybe FPM could be the issue?

**Comment by tr7zw** [comment]
Yea I had to do some stuff to render the shadow in the correct location. It might be that this has an issue with SEUS for whatever reason. I'll look into it at a later point.
