### ISSUE TITLE
{bug} animiation not display after a while using mod

### ISSUE THREAD

**Issue by Wither-Skeleton** [tr7zw/FirstPersonModel#250]
Here's Image: https://imgur.com/a/yvRdWhQ
My mod lists: https://imgur.com/a/QaS5VwP
It still work at first, but after a while it doesn't work anymore

**Comment by tr7zw** [comment]
Huh wrong repo? The First Person mod doesn't change/do any animations? In the second screen it's turned off, press F6 to reactivate it.

**Comment by Wither-Skeleton** [comment]
ahh, thanks for help! you can safely close this thread now
