### ISSUE TITLE
First person view occasionally breaks when going from third person back to first person.

### ISSUE THREAD

**Issue by Patrick12411** [tr7zw/FirstPersonModel#251]
A small bug ive noticed is that when going from third person to first person the first person view will break sometimes and force the game to be restarted.

Its important to note that I am using the Better Third Person Mod: https://www.curseforge.com/minecraft/mc-mods/better-third-person

**Comment by tr7zw** [comment]
Did you maybe accidentally press F6?

**Comment by Patrick12411** [comment]
> Did you maybe accidentally press F6?

Ah, I wasnt aware f6 was a hotkey to toggle this. Youre right! Thanks.
