### ISSUE TITLE
Glitch when using bow and crossbow that obstructs player view

### ISSUE THREAD

**Issue by ekiplier** [tr7zw/FirstPersonModel#256]
I was using the first-person model and not enough animations mods and I couldn't help but notice that there's an annoying glitch when charging a bow or crossbow and looking up at about a 50-degree angle and then turning left. The first-person view will glitch into the left arm, almost completely obstructing the view. In the crossbow's case, it can even happen with both arms. Here's a screenshot:

![image](https://user-images.githubusercontent.com/74121461/160265895-bf6dca34-b43d-447b-b08f-cb181930dba4.png)

**Comment by tr7zw** [comment]
Duplicates #56
