### ISSUE TITLE
Render about Carry On

### ISSUE THREAD

**Issue by NightSharp** [tr7zw/FirstPersonModel#257]
I have installed Carry On, NotEnoughAnimations & FirstPersonModel, and etc.
When I use Carry On to hold anything I can
The moder displays correctly in Third-Person (F5 Switch), like this
![2022-03-29_22 43 33](https://user-images.githubusercontent.com/9748063/160638571-fc075e96-ed44-43db-b4eb-e91850a9059e.png)
![2022-03-29_22 43 40](https://user-images.githubusercontent.com/9748063/160638702-6899b0ad-ada2-4e87-80b5-14cd19e93cea.png)
But when switching to First-Person, I can say nothing about my arms and what I carry on, like this
![2022-03-29_22 43 53](https://user-images.githubusercontent.com/9748063/160638964-18fe86fd-5627-4a52-8028-f7baaea83e7d.png)

**Comment by tr7zw** [comment]
#160 It's CarryOn's fault, won't fix.
