### ISSUE TITLE
About Sitting in the Boat

### ISSUE THREAD

**Issue by NightSharp** [tr7zw/FirstPersonModel#258]
Both MC-1.18.1/2
- 1.18.2
Forge-40.0.32
- 1.18.1
Forge-39.1.2

I can't see the lower half of my body when sitting in the boat, from `third person`, like this
![2022-03-30_08 14 03](https://user-images.githubusercontent.com/9748063/160726676-248a962b-6ff3-4e24-8547-1af4baa66815.png)

also, from `first person`, I would see my legs flickering, which can't be showed in a static image here.
![2022-03-30_08 23 46](https://user-images.githubusercontent.com/9748063/160727115-567a391b-3bfe-40bc-be08-d5a4e5397e4b.png)
![2022-03-30_08 23 51](https://user-images.githubusercontent.com/9748063/160727136-7b101049-9d93-4374-b313-419dff0b21f5.png)

**Comment by tr7zw** [comment]
This not related to the firstperson mod, maaybe not enough animations because there is an issue with the latest release, try the one before.

**Comment by tr7zw** [comment]
But it looks like the player is sitting too low, neither mod changes the y position/offset, so even that sounds unlikely.

**Comment by NightSharp** [comment]
> This not related to the firstperson mod, maaybe not enough animations because there is an issue with the latest release, try the one before.

I replace the NEA 1.5.0 with the 1.4.0 one.
The issue still exist

**Comment by tr7zw** [comment]
Try without either or just one of the two mods. So far no other reports of issues with boats and like I said, neither mod should be able to move the player that way. Probably some other mod.

**Comment by NightSharp** [comment]
> Try without either or just one of the two mods. So far no other reports of issues with boats and like I said, neither mod should be able to move the player that way. Probably some other mod.

Tested.
nothing about other mods, just the shader.
Complementary Shader caused this issue.
SEUS HRR 3 & SVS Extreme works fine.

**Comment by tr7zw** [comment]
Hm I play with Complementary too, never seen that issue. Check for updates of Iris(or optifine) and Complementary.

**Comment by NightSharp** [comment]
> Hm I play with Complementary too, never seen that issue. Check for updates of Iris(or optifine) and Complementary.

Here is my F3 Info
![2022-03-31_03 34 20](https://user-images.githubusercontent.com/9748063/160916379-5c531068-64a8-482d-9db5-e0e5497ecd8c.png)

I use the latest Optifine and Complementary
My Graphics Driver is NVIDIA 512.15
My Video Card is 3070Laptop

So strange.
