### ISSUE TITLE
[1.18.2 / FORGE] Curios hand items render when hand render is disabled.

### ISSUE THREAD

**Issue by KKotik** [tr7zw/FirstPersonModel#260]
Title and screen describe the issue. 
![image](https://user-images.githubusercontent.com/45950781/162008775-2c7303f5-5f3b-4b53-8409-46555ce97215.png)

**Comment by tr7zw** [comment]
The hands are turned invisible, not much I can do here I think. Either play without vanilla hands enabled, or try opening an issue at Curio to not ignore invisible body parts.

**Comment by KKotik** [comment]
Got you will open issue on their github and redirect it to there as example.

**Comment by KKotik** [comment]
Check on Curio's dev response, if there is nothing that can be done, better to close this one I guess.

**Comment by tr7zw** [comment]
Like proposed on the issue, this should be resolved by the mod adding that curio, not by Curios or FPM.
