### ISSUE TITLE
Third hand appear when looking at the map item with hand render disabled.

### ISSUE THREAD

**Issue by KKotik** [tr7zw/FirstPersonModel#261]
Title and screenshot describe the issue. 
![image](https://user-images.githubusercontent.com/45950781/162009129-621b3591-afd2-475e-b2c1-b0fd6a2a5596.png)

**Comment by endustries** [comment]
Also appears in 1.19 on fabric

**Comment by tr7zw** [comment]
Yea the 1.19 version is a 1:1 port. I haven't got around to implement the proper fix.

**Comment by tr7zw** [comment]
Fixed #222
