### ISSUE TITLE
If you pickaxe while hanging from a ladder, a punching motion appears.

### ISSUE THREAD

**Issue by wsesrdtf** [tr7zw/FirstPersonModel#262]
If you pickaxe while hanging from a ladder, a punching motion appears.

https://user-images.githubusercontent.com/101512862/162284493-7043d3c5-d24c-4144-bc0a-ed3b13230ae5.mp4

**Comment by tr7zw** [comment]
Fixed in the release I'm preparing rn. Should be on Curse in ~30 mins.

**Comment by tr7zw** [comment]
https://www.curseforge.com/minecraft/mc-mods/not-enough-animations/files/all

**Comment by wsesrdtf** [comment]
Thank you!
