### ISSUE TITLE
Right arm does not scale when scaling player model with figura

### ISSUE THREAD

**Issue by TheSnugget** [tr7zw/FirstPersonModel#263]
title
![image](https://user-images.githubusercontent.com/103380745/162632647-97f94808-03f2-4c38-b959-02c26370b41d.png)
![image](https://user-images.githubusercontent.com/103380745/162632653-c6b98bd2-999c-42e2-9d88-113592bb17ae.png)
![image](https://user-images.githubusercontent.com/103380745/162632656-9f97fc8d-9ffd-4826-9048-df7900e26faa.png)

**Comment by tr7zw** [comment]
Uhhh what. This mod does nothing with the arm other than hiding it. What are your settings? Also, note that figura sizing is not yet really technically supported.

**Comment by tr7zw** [comment]
Looking at the mod, I confused it with the other scaling mod. Sizing doesn't seem to be a direct feature of Figura, and even then the model arm is part of their model. Don't think there is anything for me to do, since I can't even test it.

**Comment by TheSnugget** [comment]
this is the script i used, !set (number) to scale
not sure exactly why it doesn't work
i use default fpm settings
[Flexible_Scaling_Script_v2.zip](https://github.com/tr7zw/FirstPersonModel/files/8459668/Flexible_Scaling_Script_v2.zip)

**Comment by tr7zw** [comment]
My best guess would be that figura assumes that it has to render the first person arm, where it has the normal scale. And since I disable the first person arm, it then scales up the 3rd person one? Maybe open an issue over there to look into it, because this mod does not have the ability to change the scale of things.

**Comment by tr7zw** [comment]
Since no one else reported issues of this kind, closing the issue.
