### ISSUE TITLE
Forge 1.18.2 incompatability with Crayfish's gun mod

### ISSUE THREAD

**Issue by Orgamorsh** [tr7zw/FirstPersonModel#266]
Using Crayfish's gun mod 1.2.6 and first person 2.1.0, guns render third person even with vanilla hands on
![Screenshot_621](https://user-images.githubusercontent.com/58994640/174230539-7af97e7f-b0c9-4a84-8774-57b65eccc6d5.png)
.

**Comment by tr7zw** [comment]
Will be "fixed" via #287 .
