### ISSUE TITLE
Issue with the FirstPerson forge mod for Minecraft Java 1.16.5

### ISSUE THREAD

**Issue by ThunderStar6097** [tr7zw/FirstPersonModel#268]
heres the crash report, idk whats going on xd
https://pastebin.com/GMGqbFFC

**Comment by tr7zw** [comment]
You didn't install the dependencies(transliterationlib).

**Comment by ThunderStar6097** [comment]
o, thanks, ok, when i used the 1.0.4 forge and fabric version of transliterationlib it worked
