### ISSUE TITLE
Twilight forest Magic Map incorrect render

### ISSUE THREAD

**Issue by aziel13** [tr7zw/FirstPersonModel#269]
The twilight forest magic map is not rendering correctly while using the first person mod's hands. It should show a map in your hands, just like a vanilla map, but is showing the map item.

![2022-07-03_16 01 19](https://user-images.githubusercontent.com/7128984/177055510-c4a5dd59-330e-4903-a01b-20f835dd1e38.png)

Minecraft 1.18.2
forge - 40.1.48
firstperson-forge-2.1.0-mc1.18
twilightforest-1.18.2-4.1.1102-universal

**Comment by tr7zw** [comment]
This has to be done by the Twilight Forest mod(adding a 3rd person rendering in general).

**Comment by tr7zw** [comment]
It's part of `autoVanillaHands` now, so it will switch the the vanilla view while holding the map.
