### ISSUE TITLE
Crash on startup M1 native mac 1.16.5 forge

### ISSUE THREAD

**Issue by grapejam2003** [tr7zw/FirstPersonModel#274]
I got crashed on startup, I have no clue to why i does. But I'm playing on 1.16.5 forge on native m1 specifically with the m1 multimc hack script, so could be because of of the rendering engine. 
Here's the crash log, I tried running it without any mods installed
[crash-2022-07-08_15.10.30-client.txt](https://github.com/tr7zw/FirstPersonModel/files/9070222/crash-2022-07-08_15.10.30-client.txt)

**Comment by tr7zw** [comment]
Hm it can't find the renderShadow method. I think there was an alternative 1.16 release on CurseForge, try that. I can't do any fixes to 1.16 anymore.

**Comment by grapejam2003** [comment]
oh okay, thanks. Version 2.0.1 seems to work fine

**Comment by tr7zw** [comment]
I think this is the same thing that now happened with Forge 1.19. They probably renamed/deleted/moved stuff during the version, breaking all/some mods in one go. Since there is a working version up too and this is just 1.16 Forge, I'll close the issue.
