### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by Purplexion** [tr7zw/FirstPersonModel#275]
Fabric modloader version 0.14.8 for Minecraft version 1.18.2, Fabric version of the mod.
Full crash log linked below.
[crash-2022-07-09_19.15.25-client.txt](https://github.com/tr7zw/FirstPersonModel/files/9078053/crash-2022-07-09_19.15.25-client.txt)

Upon trying to start minecraft with the fabric version of the mod, the game does not start and the launcher says "Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'firstperson'!"
I have confirmed this mod is at fault due to starting minecraft with this mod alone, excluding the fabric api. I'm not sure why this mod breaks now, but the mod worked perfectly fine before July.

**Comment by tr7zw** [comment]
Your config file got corrupted. Delete the firstperson json file from the config folder and it should work again.

**Comment by Purplexion** [comment]
> 

makes sense
