### ISSUE TITLE
Violent shaking of the hand occurs

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [tr7zw/FirstPersonModel#277]
**Game Version**：1.16.5
**Mod Version**：2.0.1
When I enter the game and start playing, I have a violent hand shaking problem, and I can't fix it by modifying the game configuration.I know this will be a lot of trouble for you guys but please help me anyway.
Here are the mod menus which I installed：
![VeryCapture_20220725211225](https://user-images.githubusercontent.com/102334800/180785869-a3ec9fc2-884b-46a7-8f0a-9a9d3ade89da.jpg)
![VeryCapture_20220725211256](https://user-images.githubusercontent.com/102334800/180785892-b3fe9db1-63e3-4699-ba50-c6fd2f4da281.jpg)
![VeryCapture_20220725211309](https://user-images.githubusercontent.com/102334800/180785911-2bd1d715-3953-487a-b796-9db3cc59161f.jpg)
![VeryCapture_20220725211321](https://user-images.githubusercontent.com/102334800/180785936-442eb076-fa6e-4fab-b2f9-838b3a59a909.jpg)
![VeryCapture_20220725211335](https://user-images.githubusercontent.com/102334800/180785947-b326d210-1e05-4625-9054-5dc24bb98c28.jpg)
![VeryCapture_20220725211345](https://user-images.githubusercontent.com/102334800/180785960-ad89b30f-4863-435c-9638-e560d03fe785.jpg)
![VeryCapture_20220725211425](https://user-images.githubusercontent.com/102334800/180785972-37bbc7f8-2416-45ec-acad-5177824e5f23.jpg)

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
And this only happens when my arm is raised, when my arm is naturally down everything is normal.

https://user-images.githubusercontent.com/102334800/180788938-cb6df469-0de1-4436-8fdf-61e6b81f116e.mp4


https://user-images.githubusercontent.com/102334800/180789015-20442a50-1e63-4ce5-85fe-2013423e4351.mp4

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
Forge Version：36.2.39

**Comment by tr7zw** [comment]
You might get away with disabling Smoothing from NotEnoughAnimations. 1.16 can't receive any updates anymore, so disabling that feature should work.

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
Sorry to disturb you once again but I didn't find the configuration file for NotEnoughAnimations, where can I change this configuration?

**Comment by tr7zw** [comment]
In the config folder should be a ``notenoughanimations.json``. In there set ``enableAnimationSmoothing`` to false.
