### ISSUE TITLE
1.16.5 crash on death

### ISSUE THREAD

**Issue by zargogo** [tr7zw/FirstPersonModel#278]
Whenever I get killed by any mob, the game crashes. Here are some crash logs from that:
https://crashy.net/AgGPfPtgkm6BHpnX5RVV
https://crashy.net/nTPj0qZw84g8zKCqzEmy
https://crashy.net/XkqGmIzKc3fjdX0rdAkh
https://crashy.net/UQwQ4zDiBqV5FLO0FVBQ

Then, if I try to re-join the world it crashes again. Here is the crash log from that:
https://crashy.net/Gt1XCw0J9MWQjjhcfLX7

If, instead of trying to re-join, I decide to create a new world... my model looks like this:
<img width="1440" alt="Screen Shot 2022-07-27 at 01 42 50" src="https://user-images.githubusercontent.com/17407989/181130887-1172dc55-0b6b-48b3-a1d3-79cebd2a5792.png">

**Comment by tr7zw** [comment]
Something corrupts the pose stack. Any mod can basically cause that. Since the 1.16 release has been out for a long time without anyone having issues like that, it's probably some other mod. Try removing mods till this error goes away.

**Comment by tr7zw** [comment]
Stale.
