### ISSUE TITLE
Third-party downloads are disabled

### ISSUE THREAD

**Issue by Hedwig7s** [tr7zw/FirstPersonModel#279]
Can you please enable them? Thanks

**Comment by tr7zw** [comment]
No, use Modrinth for api downloads.

**Comment by Hedwig7s** [comment]
> No, use Modrinth for api downloads.

Oh ya use modrinth now? Ight lemme find it

**Comment by Hedwig7s** [comment]
Ight ya haven't put this mod there yet

**Comment by Hedwig7s** [comment]
@tr7zw

**Comment by tr7zw** [comment]
Huh, true. Thought I did. Will do that the following days.

**Comment by tr7zw** [comment]
https://modrinth.com/user/tr7zw will be listed here then.
