### ISSUE TITLE
Crash on start-up (1.19)

### ISSUE THREAD

**Issue by ekiplier** [tr7zw/FirstPersonModel#280]
[crash-2022-08-01_00.00.15-fml.txt](https://github.com/tr7zw/FirstPersonModel/files/9229871/crash-2022-08-01_00.00.15-fml.txt)

**Comment by tr7zw** [comment]
See the other issue. Tldr: forge knowingly broke most mods. Downgrade to  .63, wait for the 1.19.1 update with a fix or give fabric a try for a better experience.
