### ISSUE TITLE
Log Spam (Hiding...Hiding...Hiding...Hiding...Hiding...)

### ISSUE THREAD

**Issue by ardissaps** [tr7zw/FirstPersonModel#282]
https://paste.atlauncher.com/view/625ea505-739d-4d5c-a3df-3332fe506b21
![image](https://user-images.githubusercontent.com/82106625/183026281-eeab6c1c-45cb-4233-8782-e6550b180dac.png)

**Comment by tr7zw** [comment]
Lesson learned, don't code at 1am 🙃

**Comment by ardissaps** [comment]
> Owner

Would you please also upload it to modrinth?

**Comment by tr7zw** [comment]
Yea when I get around to it.

**Comment by ardissaps** [comment]
Thank you sir, take your time!
