### ISSUE TITLE
Please fix this, an issue with the camera

### ISSUE THREAD

**Issue by DogeKingChris** [tr7zw/FirstPersonModel#285]
Ok so when you add too many mods from what I understand, the camera for some reason shifts back and doesn't allow you to modify it in any way in the mod config settings (the crouching x position), I believe this may be due to load order issues because I've checked EVERY mod I have, and adding over 55-60 mods just breaks it. This is a huge issue because I don't have many game changing mods, most of them are just quality of life or for the looks. And the ones that do change stuff don't change anything with the model or camera. I do have CPM, but I havent editted the vanilla animations in any way. I've had CPM installed since the beginning, and removing it does not fix the problem.
![2022-08-14_14 19 17](https://user-images.githubusercontent.com/103382195/184556683-dc554d22-5b69-4752-a43d-c5d92dc235e6.png)
 ^This is the bug, I don't know why it does this, but it completely blocks out the view. 
 It's not supposed to be in the middle of the head, it's supposed to be more forward towards the actual front of the face but for some reason it's in the middle of the head. Please fix this soon as possible, I love being able to see the first person model, but I also love being able to see what's below me in front of me.

**Comment by DogeKingChris** [comment]
By the way, thisis on 1.18.2, I hope this would be fixed on both 1.18.2 and 1.19 if possible!

**Comment by DogeKingChris** [comment]
I checked the latest 1.18.2 update logs for this mod, and it says they fixed this issue I'm talking about I think, but Idk if the creator tried it out with more mods installed. The issue very clearly is not fixed entirely

**Comment by CroaBeast** [comment]
This issue is present in 1.19

**Comment by tr7zw** [comment]
Can't fix it without knowing which mod overwrites the player offset. Could just increase the priority, but then it might just break some other mod.

**Comment by Autumnfoxbrr** [comment]
> Can't fix it without knowing which mod overwrites the player offset. Could just increase the priority, but then it might just break some other mod.

It seems to be caused by the Pehkui mod, as I've been having this issue and uninstalling pehkui suddenly fixed it, and it kinda makes sense since Pehkui is a mod that messes with the players scale.

**Comment by tr7zw** [comment]
With the new built-in api I can take a look at Pehkui to make it compatible(Since there are incompatibility issues open anyway).

**Comment by Aceplante2** [comment]
I am having this same issue and it appears to be caused by the pehkui mod? or at least it goes away if I disable the mod, which confuses me becuase a while ago I was able to use both of them at once together perfectly fine. Was there an update to the 1.18.2 forge version recently?
