### ISSUE TITLE
Feature request:black/white list for arm render

### ISSUE THREAD

**Issue by supershorty1** [tr7zw/FirstPersonModel#287]
Hellow developer:
   
     I want to suggest a feature :
      render vanilla hands when holding a black/white list item.(for mods like MrCrayfish's Gun Mod to aim,or some mods have animations in first person)

**Comment by TheEffortFighter** [comment]
If you could, could you also add this feature to 1.16.5?

**Comment by tr7zw** [comment]
Has been implemented in 2.2.2.
