### ISSUE TITLE
Worn player/mob skulls rendered in first person view, blocking vision

### ISSUE THREAD

**Issue by steven-archer** [tr7zw/FirstPersonModel#288]
Player skulls and mob skulls are shown being worn in first person, view completely blocked and can't see past the head when worn.

Mod version: 2.1.2-mc1.18.2 (Forge)

Ender dragon head being worn:
![2022-08-24_10 24 11](https://user-images.githubusercontent.com/23382181/186447842-862da7f4-68f3-4284-a20f-c6686abd43cf.png)
![2022-08-24_10 25 24](https://user-images.githubusercontent.com/23382181/186447862-f4fb7fc5-d223-4fdc-9ebd-a16027d9601d.png)

Skeleton head being worn:
![2022-08-24_10 24 27](https://user-images.githubusercontent.com/23382181/186447912-3815145c-9c28-4589-b154-d095505c1961.png)
![2022-08-24_10 25 13](https://user-images.githubusercontent.com/23382181/186447936-bfddc598-8895-4e18-9f16-6fe976b95335.png)

Player skull being worn:
![2022-08-24_10 24 33](https://user-images.githubusercontent.com/23382181/186447945-5b0a8e46-b68f-46e9-8435-925fa0cc01bb.png)
![2022-08-24_10 25 01](https://user-images.githubusercontent.com/23382181/186447954-7437f803-7297-4878-8172-0ca609a3d7c9.png)

**Comment by tr7zw** [comment]
You have a conflicting other mod installed that changes the player model or armor rendering.
