### ISSUE TITLE
[Bug] [Suggestion] Compatibility with Better Combat.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [tr7zw/FirstPersonModel#292]
You can see your entire upper body when swinging your weapon with both this and Better Combat installed. A simple solution would be to add an option to render only the arms, and remove the body. 

"Then what's the point of using this mod?"

Well, arm movement feels a lot more realistic with this mod. I'd love to keep that, while still being able to use Better Combat without seeing my body detach itself from the head No, I didn't say that backwards. :)

![2022-09-05_22 39 59](https://user-images.githubusercontent.com/60951301/188535768-ddad4db9-05be-4bd5-a038-e36b021c4834.png)
![2022-09-05_22 40 37](https://user-images.githubusercontent.com/60951301/188535772-ab7bd86c-4399-4684-9e36-732d434f6713.png)

It looks _slightly_ better in the second pic where I'm aiming straight ahead, but in the first where I'm aiming down, that's an eyesore.

**Comment by Landrozaum** [comment]
this is an animation issue of better combat, this mod animates the player with the upper part of the body going to the front, so the "neck" in first person go to front

**Comment by tr7zw** [comment]
Known issue and it's on the todo.
