### ISSUE TITLE
Load loop on Fabric when adding First Person (1.18.2)

### ISSUE THREAD

**Issue by Vinson8970** [tr7zw/FirstPersonModel#298]
https://user-images.githubusercontent.com/108201128/192680530-b9a45af9-0161-4ded-affa-47ddffbf3e7d.mp4

[Fabric.txt](https://github.com/tr7zw/FirstPersonModel/files/9661208/Fabric.txt)

(my mouse animation freezes when recording, sorry)

**Comment by tr7zw** [comment]
Need the latest log of this happening. Load loop usually means something in the resource loading fails.
