### ISSUE TITLE
Cannot View Chestplates with Vanilla Hand Enabled 

### ISSUE THREAD

**Issue by CosmicChrisss** [tr7zw/FirstPersonModel#303]
Only config I changed was enabling the vanilla hand option, however when I look down I don't see my equipped chestplate. I'm unaware if this is intentional or not. 

Additionally, a potential feature I'd love to see would be to toggle each hand being vanilla style or not, For example having your vanilla hand but having a first person left hand. Appreciate the work you do. Let me know!

![Screenshot_2](https://user-images.githubusercontent.com/5308590/197654914-de771f6c-1a80-4976-a9c7-aa5935c6e023.png)
![Screenshot_4](https://user-images.githubusercontent.com/5308590/197654918-d96894f2-8551-469e-a7aa-b560d0cb3739.png)

**Comment by frostyfawxy** [comment]
would love a fix for this!

**Comment by tr7zw** [comment]
This has been resolved some time ago.
