### ISSUE TITLE
[Enchantment] FirstPersonModel + minecraftPlayerAnimator

### ISSUE THREAD

**Issue by ChickChuck2** [tr7zw/FirstPersonModel#305]
I use minecraftPlayerAnimator along with FirstPersonModel and I'm having a bit of an annoying problem when I enter combat mode with something. Follow this video to see the problem

[DIAJDASDKAS VIDEO](https://streamable.com/poh3tj)

If possible implement something that would help solve this problem, or recommend some other mod

Mod: https://github.com/KosmX/minecraftPlayerAnimator

**Comment by tr7zw** [comment]
This issue is a bit lost, has been implemented long ago.
