### ISSUE TITLE
1.19.2 Horn animation causes crash

### ISSUE THREAD

**Issue by Freeflier** [tr7zw/FirstPersonModel#308]
The new horns in 1.19 must have a new animation, as they cause a crash with the first person mod. Specifically, it calls this error: `applyTransform() must not be called on a vanilla ArmPose!`

 Tested it with just this mod, with the latest version of the mod and Forge 43.1.1. Attaching the crash report.

[crash-2022-11-06_01.01.54-client.txt](https://github.com/tr7zw/FirstPersonModel/files/9945430/crash-2022-11-06_01.01.54-client.txt)

**Comment by tr7zw** [comment]
If I remember correctly, that was a forge bug, so update your Forge install. Not a FirstPersonMod issue.
