### ISSUE TITLE
[1.19.2]Unexpected error on Startup

### ISSUE THREAD

**Issue by OcrSu** [tr7zw/FirstPersonModel#309]
[crash-2022-11-04_15.53.30-client.txt](https://github.com/tr7zw/Exordium/files/9937635/crash-2022-11-04_15.53.30-client.txt)
[latest.log](https://github.com/tr7zw/Exordium/files/9937637/latest.log)
Win11
GT1030 DDR5
Ryzen5 5600

**Comment by tr7zw** [comment]
Ah no, you have a "freecam" mod installed, but it's not https://modrinth.com/mod/freecam. Apparently it's https://www.curseforge.com/minecraft/mc-mods/freecam-by-zergatul , that just reuses the same mod id. Going to open the issue there.
