### ISSUE TITLE
Add advanced options to manually enable or disable specific mixins

### ISSUE THREAD

**Issue by TsukiTheDwagon** [tr7zw/FirstPersonModel#312]
What it says on the tin. There's a specific use case I have that I want to disable a mixin manually, but there's not really an option to do that in the config menus.

Would be nice to have, I recall some other fabric mods offering a similar option like BedrockIfy.

**Comment by TsukiTheDwagon** [comment]
I just realized I might actually need a specific config option and not just disabling mixins. I'll leave this open just in case, feel free to disregard this (or add it if you want)

**Comment by tr7zw** [comment]
Can you give any use cases? If it's just something hyper-specific, you can technically disable targeted mixins of any mod by opening the jar with 7zip/winrar and modifying the mixin json file to not contain that line.

**Comment by TsukiTheDwagon** [comment]
Well there was actually a specific mod incompatbility I had in mind, and it doesn't seem disabling any mixins would specifically stop it, I made this issue when I thought it would.

There's a mod I use called Figura that lets you make custom playermodels, and there's this Lua function in it called partToWorldMatrix which gets the world position of a model part. 

It's somewhat useful for setting the point of view of the first person camera to match your figura model, but slight problem: It stops working when the model is hidden, which happens when flying with elytra or going from the swimming movement back to a neutral position.

This ends up causing the camera to freak out. I was trying to see if maybe there was a way to stop the mod from hiding the playermodel automatically in those cases altogether, and i thought the elytra mixin was the culprit but it turns out it's spread across more of the mixins.

**Comment by tr7zw** [comment]
Why does the camera freak out, shouldn't it just use the vanilla camera(+invisible player), so it's just fine?

**Comment by TsukiTheDwagon** [comment]
I'm manually setting the camera pivot point to said part's location, and since the part gets sent way out of view when it's hidden, the camera gets flung over there as well.

**Comment by tr7zw** [comment]
Oh wow, ok yea, never thought that something like that could happen(the sending away part is to move stuff out of the way, that refuses to check for the hidden flag).

**Comment by TsukiTheDwagon** [comment]
Is it possible you can have the hiding toggles be split into head and body though? Because in my specific use case, the head still needs to be hidden and sent out of the way, but the body should not be.

**Comment by tr7zw** [comment]
Not really. Doesn't sound right to build in a toggle that just causes visual issues because of this^^. I doubt anyone else has this issue, so the simplest way might be that you just remove/comment out the 2 lines and let it build a jar for you to use.

**Comment by TsukiTheDwagon** [comment]
Where are the lines that actually send the part out of the way? I couldn't find what mixin those were in.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/FirstPersonModel/blob/1.19/Shared/src/main/java/dev/tr7zw/firstperson/mixins/ModelPartMixin.java#L25 But you probably don't want to touch that, since it just might break compatibility with other mods. 
This is the commit you are probably looking for https://github.com/tr7zw/FirstPersonModel/commit/df38a84b586c18ca1cb5e94ecb3cac4f94c8d221#diff-83a50c262a972f3d0fcc1301e5dc7c5caf15bc581c664ec90fd5c10226062e2bR36

**Comment by tr7zw** [comment]
But looking at that, the body is never moved far away. It's only getting done to the head. Also during elytra flying, the model is not rendered at all. So possible it's more an issue with the lua script(that it doesn't check if the model is rendered at all)?

**Comment by TsukiTheDwagon** [comment]
It only really gets sent super far out with shaders enabled for some reason, not sure if that has to do with anything

**Comment by TsukiTheDwagon** [comment]
hmm though, disabling the code for checking when i'm swimming doesn't seem to solve the issue for some reason, and even with iris disabled the view still seems to glitch a little bit

**Comment by tr7zw** [comment]
Aha, I think I know whats going on. That might be the positions used for the shadow calculations? What happens when you press f6/use f5 mode?

**Comment by TsukiTheDwagon** [comment]
wait a minute! when i disable the first person model and look at the coordinate output, with shaders off it stays in place but when they're turned on the water waving and refraction seems to be messing with the coordinate values

**Comment by TsukiTheDwagon** [comment]
that still doesnt seem to account for the model in first person not tracking the position properly when exiting a sprint swim though

**Comment by tr7zw** [comment]
I think in general, the issue is probably the approach. You want the model to be in the right place for the camera(because your model is at a different height than steve). So just moving the camera up with the lua script or some other mod should do the entire trick? Left/Right should be fine(as long as the head is centered) and back/forth is already a setting.

**Comment by TsukiTheDwagon** [comment]
My situation is a lot more complex than that because the body actually gets rotated around in the animations themselves which affects the head position, moving it forwards and backwards as well as up and down dynamically.

Also not sure why with shaders on the position gets sent like over 2 million blocks away on one of the frames

**Comment by TsukiTheDwagon** [comment]
and the issue seems to be *specifically* with exiting a sprint swim, all the other cases seem to work perfectly aside from that one thing

**Comment by tr7zw** [comment]
I mean, you might be a lot better off just making a compatibility hook https://github.com/tr7zw/FirstPersonModel/blob/1.19/Shared/src/main/java/dev/tr7zw/firstperson/api/PlayerOffsetHandler.java

**Comment by tr7zw** [comment]
> and the issue seems to be _specifically_ with exiting a sprint swim, all the other cases seem to work perfectly aside from that one thing

when entering/exiting swim mode, the model does a tilt animation. Possible that it messes some other logic up(since the player model does fully get rendered when exiting, but isn't straight up yet).

**Comment by TsukiTheDwagon** [comment]
that's kind of strange though because it only happens in first person, not third person

**Comment by TsukiTheDwagon** [comment]
eh though i kinda give up debugging for now, there's so many factors to this that i don't even know where to continue.

The issue doesn't seem to be linked directly to this mod though as far as I can tell from what I've checked, it's likely one of those nightmare incompatiblity scenarios where various mods clashing together cause a single issue...

Closing issue for now, I'll reopen if I find something else that might be causing it in here.

**Comment by TsukiTheDwagon** [comment]
Update: The other mod (Figura) fixed the incompatibility on their end.

It works now!
