### ISSUE TITLE
[1.19.2 Fabric] Hats (AKA items with models) with the mod "Essential" installed forces hats to render in firstperson.

### ISSUE THREAD

**Issue by XFAXIO** [tr7zw/FirstPersonModel#315]
I tested to see why this happened and saw it was because the mod **Essential** (Fabric).
There probably wont be a fix to this issue, but if there was a option in the in the config file to **_"Disable All Hats"_** in firstperson, it would be a nice fix for Essential and other mods that mess with the playermodel. If that's possible to implement.

**Here's an example:**
![image](https://user-images.githubusercontent.com/80545554/205419454-253d7191-9ef7-46c5-9c6a-93c0f820afdf.png)
![image](https://user-images.githubusercontent.com/80545554/205419507-b235e095-8de1-46ae-9af8-4597437c573b.png)

**Comment by Fox595676** [comment]
I'm having this too, and it's very irritating! I have the antlers on my skin, and they're covering up the screen a lot.
![image](https://user-images.githubusercontent.com/81087203/209429961-f68a9e80-77f9-4818-b61d-66305434987f.png)
![image](https://user-images.githubusercontent.com/81087203/209429963-221f8aea-90b6-46c7-939a-6244172b888d.png)
![image](https://user-images.githubusercontent.com/81087203/209429964-6d233b59-6cb8-403e-8c71-5188f922c9b7.png)
And the Essential cap is one of the worst, as you've seen in the pictures
![image](https://user-images.githubusercontent.com/81087203/209430059-5125ff50-6cd2-44dd-90e3-9c54355a481c.png)

**Comment by tr7zw** [comment]
This needs to be fixed from Essentials side. They render the hats incorrectly.

**Comment by XFAXIO** [comment]
Could it be possible to shift the hat part of the playermodel **behind** the camera in first person? If it's behind the player they cant be seen at all even if a mod renders hats incorrectly; Or make hats so **small** that they can't be seen at all?

Maybe it _could_ solve cases like this if mods dont work as intended with this mod, Even as a **band-aid fix**.

**Comment by tr7zw** [comment]
> Could it be possible to shift the hat part of the playermodel behind the camera in first person?

And that's exactly how all helmets/blocks on head/mod cosmetics usually get hidden. But essential clearly doesn't the vanilla render logic, so it doesn't work. This is not a bug of this mod, this is an Essential bug.

**Comment by tr7zw** [comment]
Please report this issue to them, so they can look into it. I can't fix this for their closed-source system.

**Comment by tr7zw** [comment]
Tested with the Essential cap, can not reproduce anymore on 2.2.3.
