### ISSUE TITLE
Minecraft loading screen fades in and out repeatedly

### ISSUE THREAD

**Issue by nNoav** [tr7zw/FirstPersonModel#318]
![epilepsy](https://user-images.githubusercontent.com/102281810/208448269-febc2c08-50af-464d-b1ce-87040bbb2661.gif)

I’ve disabled each of my mods one by one and this mod seems to be the one causing issue. This is 1.19.2 Fabric, if that helps.

**Comment by tr7zw** [comment]
Need the latest log to tell you whats going wrong.

**Comment by nNoav** [comment]
Sorry, here’s my log.
[2022-11-28-1.log](https://github.com/tr7zw/FirstPersonModel/files/10260026/2022-11-28-1.log)

**Comment by tr7zw** [comment]
That was a normal start? There are no errors in there.

**Comment by nNoav** [comment]
Ah, I’ve given you the wrong one, terribly sorry. Here’s the lastest for real this time.
[latest.log](https://github.com/tr7zw/FirstPersonModel/files/10260080/latest.log)

**Comment by tr7zw** [comment]
> @Redirect conflict. Skipping firstperson.mixins.json:PlayerRenderMixin from mod firstperson->@Redirect::setModelPoseRedirect(Lnet/minecraft/class_1007;Lnet/minecraft/class_742;Lnet/minecraft/class_742;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000, already redirected by skinswapper.mixins.json:preview.PlayerEntityRendererMixin from mod skinswapper->@Redirect::setModelPoseRedirect(Lnet/minecraft/class_1007;Lnet/minecraft/class_742;)V with priority 1100

Skinswapper is incompatible, because they redirect the same method this mod needs to redirect(and their mod technically doesn't). Remove Skinswapper and it will work.
