### ISSUE TITLE
Crouch Y offset off w/ Pehkui mod

### ISSUE THREAD

**Issue by RicoR3t** [tr7zw/FirstPersonModel#321]
For some reason the model moves down a bit when I shift. Is there some way I can change the Y as well?
![bug](https://user-images.githubusercontent.com/121584165/209881027-6a2e49ae-661a-4861-8975-98bddba2c875.png)

**Comment by tr7zw** [comment]
This mod doesn't touch the camera at all. And the player model does get a bit lower when crouching... That is the definition of crouching? I don't understand what the question is.

**Comment by RicoR3t** [comment]
Yes, but I don't think the movement amount for the crouch is scaled along with the scale from pehkui. Thus, making it so that the crouch as a small model is the same amount as a large model which ends up putting the model underground. Idk if you have a way of fixing this. And it's good if you can't. I know nothing about programming, so you're the expert here.

**Comment by tr7zw** [comment]
Again, I don't move the model or the camera on the y at all. So if these don't match up, that's up to Pehkui. Added to that, the Pehkui is currently not even supported( #249 ).

**Comment by RicoR3t** [comment]
ight, kk, ill just deal with it then. Thanks!
