### ISSUE TITLE
[Suggestion] Request to add viewpoint X, Y offset in config

### ISSUE THREAD

**Issue by TinyblackQvQ** [tr7zw/FirstPersonModel#323]
When using Mods like _Minecraft Comes Alive_ which could change the players' model height, the first person viewpoint will still be default.
That caused a problem that when player is too much tall or short, the field of view will be covered by tools, models, or no hands, tools rendered untill the player looks down.
Specially when using mod weapons, tools which are conspicuous and garish, the problem will happen more seriously.

**Comment by tr7zw** [comment]
Changing the camera position is not something planned for this mod.

**Comment by TinyblackQvQ** [comment]
Got it, thanks for your reply.
