### ISSUE TITLE
[Compat] Charm's atlas doesn't render properly

### ISSUE THREAD

**Issue by ryleu** [tr7zw/FirstPersonModel#327]
![image](https://user-images.githubusercontent.com/69326171/211473188-633bf29d-5d7c-4ae4-bdff-7eb50c838ddb.png)

Charm's atlas doesn't render as expected. It should look like a vanilla map, rather than just the item.

With vanilla hands enabled, it works fine:

![image](https://user-images.githubusercontent.com/69326171/211473375-e4b9e854-1403-4a06-a0e9-f4f1b638db06.png)

**Comment by tr7zw** [comment]
Add the item name into the config to auto-trigger vanilla hands when holding this item. You can also make a pull request adding it to the default config.
