### ISSUE TITLE
Hand blocks spyglass

### ISSUE THREAD

**Issue by Aceplante2** [tr7zw/FirstPersonModel#332]
Title. Not sure if it is this mode alone but I also use it with not enough animations, but whenever I use spyglass i have to keep shifting my player becuase the hand constantly blocks the lens

**Comment by tr7zw** [comment]
Duplicate of already fixed #222

**Comment by Aceplante2** [comment]
forge 1.18.2 by the way

**Comment by tr7zw** [comment]
Nep. Still already fixed in 2.2.2. Releasing 2.2.3 rn for 1.18.2, it's still fixed.

**Comment by tr7zw** [comment]
The mod turns off while scoping, so should be gone for good.
