### ISSUE TITLE
sit

### ISSUE THREAD

**Issue by FanRenLa** [tr7zw/FirstPersonModel#333]
![QQ截图20230208173942](https://user-images.githubusercontent.com/83486178/217493264-e59795d8-2db9-49fe-8e20-fb06c8f91c38.png)
![QQ截图20230208174343](https://user-images.githubusercontent.com/83486178/217493566-b12b8b9b-4599-457f-907d-eeb5da115db1.png)
firstperson-forge-2.2.0-mc1.19.2
sit-1.19-1.3.3

**Comment by FanRenLa** [comment]
Large error.

**Comment by FanRenLa** [comment]
In addition, can you add other axis adjustments.

**Comment by tr7zw** [comment]
Duplicate of #77
