### ISSUE TITLE
[SUGGESTION] Compatibility

### ISSUE THREAD

**Issue by Willem07** [tr7zw/FirstPersonModel#334]
**Is it possible to make compatibility with Epic Fight by switching the first-person view. For example, when I switch to Epic Fight combat mode the first-person view of your mod is disabled and vice versa**

**Comment by tr7zw** [comment]
I have sent the developer of Epic Fight everything he needs to know to make the mods compatible. I have no intention to further add anything from my end, especially with alternatives like Better Combat.
