### ISSUE TITLE
Exeption Feature

### ISSUE THREAD

**Issue by Dekmatik** [tr7zw/FirstPersonModel#336]
As far as i can remember in "Real First Person 2" you could make exeptions for the rendered arms in the config menu. So you could install mods that already had animations like gun mods. Would nice to have this feature, too.

**Comment by tr7zw** [comment]
Already a thing.

**Comment by Dekmatik** [comment]
But how can i just make some items a exeption like in real first person 2?
This option just changes the setting overall.

**Comment by tr7zw** [comment]
> This option just changes the setting overall.

It renders the item like vanilla when holding it(basically an exception).

**Comment by Dekmatik** [comment]
> `autoVanillaHands`

Yea, but only works for all items and not specific. Thats what i meant. You could decide what items you'd like to use with vanilla arms and which you would use the third person model in the config.

**Comment by tr7zw** [comment]
Read again. I'm not talking about the vanilla hands toggle in the settings. I'm talking about the field in the config, where you can enter items to be rendered like vanilla.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/221255542-597e4aa4-5c0e-4913-8744-41cc2fc55b81.png)

**Comment by Dekmatik** [comment]
I apologize. You're right. We both talked about the config folder, but i did not drag the latest update there therefore this line wasn't there. Again im sorry and thankful for your help.
