### ISSUE TITLE
Helmet blocks view

### ISSUE THREAD

**Issue by Satanaelcode** [tr7zw/FirstPersonModel#337]

**Comment by Satanaelcode** [comment]
So there is this mod where you can get this helmet but it is a custom model that is littery in front of you head so you dont see anything if you have the playermodel thig in it

**RECOMMANDATION**

Make a config (please) thats lets the player make it able to enable rendering spesific parts for example helmet so you can disable it IF you run into any problems based on compatibily that makes it easier for modpack makers to intigrate the mod with others

**Comment by Satanaelcode** [comment]
so long this is not intigrated or anything simular then that i cant use the mod so organic like i would love to so i cant intigrate it into my projets for now

wish this to be fixed

**Comment by tr7zw** [comment]
Having the helmet visible is NOT intended. You have some incompatible mod installed that renders the helmet incorrectly(either the mod adding the helmet or a mod modifying the player model).
> Make a config (please) thats lets the player make it able to enable rendering spesific parts for example helmet so you can disable it 

The mod literally does everything in it's power NOT to render the helmet.
Open a ticket at the mod that is messing it up(either the player model itself or the mod adding the broken helmet).
