### ISSUE TITLE
Compatibility with better combat

### ISSUE THREAD

**Issue by 48004800** [tr7zw/FirstPersonModel#338]
https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/4413547
https://beta.curseforge.com/minecraft/mc-mods/playeranimator/files/4417488
https://beta.curseforge.com/minecraft/mc-mods/first-person-model/files/4417084

**Comment by 48004800** [comment]
![2023-03-02_10 19 15](https://user-images.githubusercontent.com/78255094/222315156-8f6a1287-8dae-43b3-8251-42158473ce16.png)

**Comment by Aceplante2** [comment]
Are you saying the issue is the fact your body seems to disconnect below you when you attack? Maybe the pov should change too?

**Comment by tr7zw** [comment]
This mod has better combat compatibility. The model gets moved on the x/z to stay behind the camera. y isn't used, since the camera shouldn't move.
