### ISSUE TITLE
Compatibility with "Kelvin's Better Player Animations"

### ISSUE THREAD

**Issue by mrcrashmer** [tr7zw/FirstPersonModel#339]
I figured out a little bit about this issue, the problem is the constant display of a duplicate layer of the skin in first-person mode. This is definitely a problem with the animation mod. It would be nice if you find a solution, I'm not sure there is a way to get through to the author in the near future.
Too bad I'm not competent in this matter myself, so would have created a fork.
This mod on the animations uses the animation library, which are made by a bunch of other mods.
What I mean by that? In fact, the difference between this mod and others only in the animations themselves, but other mods work fine with [FirstModel], so I'm a bit stumped.

Here's the link by the way - https://github.com/Kelvin285/KelvinsBetterPlayerAnimations
![image](https://user-images.githubusercontent.com/90141892/222832693-573ad33d-11c8-4c5c-864c-27e283eba151.png)

**Comment by tr7zw** [comment]
Huh, never heard of that mod before, but from the positioning alone it looks like a custom player model. I did add some API that other mods can hook into to know when they shouldn't render the head/offset the player model to be lined up with the camera(used for betterCombat). So the author could implement this and get in contact for questions.

**Comment by mrcrashmer** [comment]
That was a pretty quick response, didn't even think about the possible "custom player model". In any case, this is the only mod that changes the animation of movement in Fabric 1.19.3. At least the others i do not know, Im wrote to the developer mod, I hope to wait for an answer. :)

**Comment by tr7zw** [comment]
Closing this. There are multiple ways for the mod author to get this working perfectly fine while also making the mod better compatible with other mods. I think that should be preferred about me hacking in some one-time workaround.
