### ISSUE TITLE
It crashed on start.

### ISSUE THREAD

**Issue by Zorro-no** [tr7zw/FirstPersonModel#340]
This mod keeps crashing on start bc yes. i need help.
crash report:[crash-2023-03-04_19.59.59-client.txt](https://github.com/tr7zw/FirstPersonModel/files/10889432/crash-2023-03-04_19.59.59-client.txt)
Log:[latest.log](https://github.com/tr7zw/FirstPersonModel/files/10889433/latest.log)

**Comment by tr7zw** [comment]
The mod "identity" is crashing. Might be a hard incompatibility between that mod and this mod.

**Comment by Zorro-no** [comment]
ok, thanks. ill tell you if it crashes again
