### ISSUE TITLE
Looking down and crouching while on an edge causes me to fall because of sitting

### ISSUE THREAD

**Issue by Dino730** [tr7zw/FirstPersonModel#341]
This is really annoying and I've died multiple times because of this. Please just add an option in the settings to remove sitting or have a keybind for it.

**Comment by tr7zw** [comment]
Sitting is not part of this mod. This mod doesn't change any movement/collision mechanics and is purely visual.

**Comment by Dino730** [comment]
I'm stupid. I forgot about another datapack I installed that added sitting and I thought it was this mod because of the sit X option in the settings lmao
