### ISSUE TITLE
not ending loading screen

### ISSUE THREAD

**Issue by WillowWhyTfIsThisTaken** [tr7zw/FirstPersonModel#342]
if i use the mod in combination with skin swapper the loading screen is in a non ending loop

**Comment by tr7zw** [comment]
Skinswapper overwrites a mixen, causing the client to get stuck. It's not compatible.

**Comment by WillowWhyTfIsThisTaken** [comment]
is there a alternative to eitehr skin swapper or firstpersonmodel?

**Comment by tr7zw** [comment]
Not that I know. This is something skin swapper can fix, by removing that unused(unnecessary) mixin.

**Comment by WillowWhyTfIsThisTaken** [comment]
ok tysm ill open an issue on the skin swapper site
