### ISSUE TITLE
Compatibility with cgm

### ISSUE THREAD

**Issue by supershorty1** [tr7zw/FirstPersonModel#343]
add guns into autoVanillaHands but 3rd person gun still visible
![CAZSV0ECA2ABKO05IZ(@6$O](https://user-images.githubusercontent.com/111652379/224544619-42c3ce1c-36b5-4340-ae4a-45e6d1ab7f7e.png)

**Comment by Barerock** [comment]
I don't even see a config or any instruction for adding things to Auto Vanilla Hands. Quite infuriating.

**Comment by tr7zw** [comment]
For now tracked in #357
