### ISSUE TITLE
Worlds won't load.

### ISSUE THREAD

**Issue by HeroRyker** [tr7zw/FirstPersonModel#345]
I've been having issues when using this mod. I try to load into a world, and the game crashes. I know it's this mod, I've tested. I get the error "java.lang.NullPointerException: Cannot invoke "net.minecraft.class_897.method_3933(net.minecraft.class_1297, net.minecraft.class_4604, double, double, double)" because "$$5" is null"

**Comment by HeroRyker** [comment]
crash report: https://pastebin.com/virdyzXa

**Comment by tr7zw** [comment]
There is no 1.19.4 version currently. You are trying to use the 1.19.3 version.

**Comment by HeroRyker** [comment]
I thought that versions would work as long as they started with the same 1.19 or whatever the first numbers are.

**Comment by tr7zw** [comment]
That was the case pre 1.19. But since 1.19.x contains 1.20 updates, and in general, Mojang changing however much they want, each 1.19 update needs its own release.

**Comment by HeroRyker** [comment]
Ah. Thank you.
