### ISSUE TITLE
I need some help with the api

### ISSUE THREAD

**Issue by RazorPlay01** [tr7zw/FirstPersonModel#348]
I am creating a mod which modifies the vanilla animations of the player through the player animation api. In addition to this, I am modifying the rendering of the player entity and adding tilt/oscillation depending on the direction of movement of the player. When doing this I have noticed that the Player's head is rendered on the first person screen when using your mod.  Therefore I would like to know how I could disable the rendering of the head as long as your mod is active

**Comment by RazorPlay01** [comment]
How can I import the mod through Maven I don't know much about it to be honest

**Comment by tr7zw** [comment]
https://docs.modrinth.com/docs/tutorials/maven/

**Comment by RazorPlay01** [comment]
Thanks for the support
