### ISSUE TITLE
The players shadow is still misplaced

### ISSUE THREAD

**Issue by robit4** [tr7zw/FirstPersonModel#350]
The player's shadow is still misplaced please fix.

**Comment by tr7zw** [comment]
Any more info? Mc version? other mods? forge or fabric?

**Comment by robit4** [comment]
Mc 1.19.2 Forge and a lot of mods 57 mods to many names sorry.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/234124771-dfef5398-b2d9-4b86-98b4-3e1619fa6b43.png)
![grafik](https://user-images.githubusercontent.com/5133936/234124780-2ebe8f11-da2d-4d92-92a3-b6f5a5460f38.png)
It's fixed in 1.19.4.

**Comment by robit4** [comment]
Please fix in 1.19.2 ok?

**Comment by tr7zw** [comment]
Not an issue in 1.19.2. That was fixed in 2.2.2 already.

**Comment by robit4** [comment]
Oh

**Comment by robit4** [comment]
It keeps crashing

**Comment by tr7zw** [comment]
2.2.2 has been out for nearly 6 months, that version is fine. Also just released 2.2.3 with other fixes. Otherwise open a new issue with the crash report.

**Comment by robit4** [comment]
Well the mod is not compatible with identity mod fair enough

**Comment by tr7zw** [comment]
Hm, Identity had some really cursed 3-way mod clash if I remember correctly. Yea not looking into that rn.

**Comment by tr7zw** [comment]
Added a DIY fix in #353 .
