### ISSUE TITLE
map problem

### ISSUE THREAD

**Issue by SamDevil1q** [tr7zw/FirstPersonModel#351]
i cant use the treasure map for some reason

**Comment by tr7zw** [comment]
Perhaps missing not enough animations?

**Comment by sombrae** [comment]
hey, I'm having the same issue. The map will appear black when held on any hand, and turning on vanilla hands makes maps render just fine. I do have not enough animations.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/235363504-e436bcab-f95f-4364-b1e1-9ff7ae3c4661.png)
Can't reproduce in 1.19.4 Fabric

**Comment by sombrae** [comment]
see my edit above.

**Comment by tr7zw** [comment]
Like I said, with it works with 1.19.4 Fabric, Iris, Sodium and some other mods. Also, these maps are 1:1 the same as normal maps. So if one works, the other does too. Seeing that this looks heavily modded, some mod may mess with these maps to add some features.
![grafik](https://user-images.githubusercontent.com/5133936/235363964-b77b5caa-66c9-4d68-969b-1ab1d09e8f22.png)
![grafik](https://user-images.githubusercontent.com/5133936/235364009-7fe127ba-28bb-42eb-9021-45d48d7db6cc.png)

Shaders work too, here with Complementary Reimagined and rethinking voxels(to be fair, it's a complementary fork).

**Comment by SamDevil1q** [comment]
the map Stays in my hand . i cant open it at all

**Comment by tr7zw** [comment]
Then you are missing the dependency Not Enough Animations. This issue is also at the wrong repo for the black issue.

**Comment by SamDevil1q** [comment]
i am sorry i am new to this ? so i cant fix it ?

**Comment by tr7zw** [comment]
https://modrinth.com/mod/not-enough-animations this is the mod that adds the 3rd person map holding.

**Comment by SamDevil1q** [comment]
thanks a lot ! man
