### ISSUE TITLE
Incompatibility with Create

### ISSUE THREAD

**Issue by natrow** [tr7zw/FirstPersonModel#352]
When holding certain items (Creative Worldshaper, Potato Cannon, Extendo Grip) the custom first-person model is still visible

**Comment by Hyperbus02** [comment]
It is pretty irritating, but I think this is an issue that needs to be fixed on Create's side. Either that or a configuration option is added to FirstPersonModel that allows you to add certain items to an exceoption list that doesn't render in first person.

**Comment by Churchexe** [comment]
> You could add them to the `autoVanillaHands` setting. But yea, otherwise might need fixing from creates side.

where do you find this setting? I'm looking in firstperson.json and I'll I can see are enabledBYDefault, xOffset, sneakXOffset, sitXOffset, renderStuckFeatures, vanillaHands, doubleHands, and forceActive. (which are bool, num, num, num, bool, bool, bool, bool respectively, none of them allow me to give a list of exceptions)

**Comment by tr7zw** [comment]
That config entry was added in 2.2.2.

**Comment by Churchexe** [comment]
ah, okay, the update from 2.2.0 to 2.2.3 was just uploaded to curseforge today from the looks of it so I didn't realize it had updated.

**Comment by Churchexe** [comment]
![image](https://github.com/tr7zw/FirstPersonModel/assets/39103942/b053f34b-0549-4bea-9c85-feae275b9483)
In GDlauncher at least it only shows the last update being months ago, straight from 2.2.0 to 2.2.3

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/0c820b0b-e83a-4391-b933-5914a9994cb2)
Thats some issue with GDLauncher.

**Comment by piscopancer** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/b0790e0d-5210-447e-8af8-eb4541e49806" />

i disabled potato cannot in `autoVanillaHands` for it render in real 3d, and now i have two of them, the vanilla one is not gone. What do I do? 1.21.1
