### ISSUE TITLE
Chest plate not rendering in first person (Vanilla Hands Enabled, Fabric)

### ISSUE THREAD

**Issue by sadboiweedpound** [tr7zw/FirstPersonModel#354]
For some reason, chest plates won't render on my character's body in first person. I'm not using any other mods besides this one and its dependencies. Tried finding any settings in this mod and not enough animations that might've disabled this, but I haven't found anything.

**Comment by sadboiweedpound** [comment]
Forgot to mention this is with the "Vanilla Hands" option turned on. I remember in previous the chest plate showed with this option on, but for some reason it doesn't anymore. I don't know if this is intended or not.

**Comment by tr7zw** [comment]
This has been resolved.
