### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by VirusTechie** [tr7zw/FirstPersonModel#356]
the first person model will work but randomly just stops working despite still being active on my mods tab 
![image](https://github.com/tr7zw/FirstPersonModel/assets/92647325/89117c8c-e792-4390-8421-4eab0e547625)
![image](https://github.com/tr7zw/FirstPersonModel/assets/92647325/179258d3-1346-4af9-9876-e8d0fd1c050a)
can someone help?

**Comment by tr7zw** [comment]
You pressed F6.
