### ISSUE TITLE
Translucent skin see-through error.

### ISSUE THREAD

**Issue by surfishs** [tr7zw/FirstPersonModel#359]
Translucent outer layer of Minecraft skin material will result in a translucent torso in the first person, directly see the ground behind the skin.
![image](https://github.com/tr7zw/FirstPersonModel/assets/96485650/7ec0821d-ae63-4283-b537-cb50315f6b6d)
![image](https://github.com/tr7zw/FirstPersonModel/assets/96485650/696ddb1a-c9f6-4b66-a7e1-e67fa4f0533d)

**Comment by tr7zw** [comment]
Probably more related to 3d Skin Layers. Transparency in general is a pain in the ass to get right, you could try changing to the slower render mode in 3d skin layers, that might fix some transparency issues.

**Comment by surfishs** [comment]
> Probably more related to 3d Skin Layers. Transparency in general is a pain in the ass to get right, you could try changing to the slower render mode in 3d skin layers, that might fix some transparency issues.

![image](https://github.com/tr7zw/FirstPersonModel/assets/96485650/ffae97b0-3f72-44a8-b43f-7b7d2ce30fc3)
I tried removing all my modules, leaving only 3dskin and first person, the problem disappeared and I will continue testing.
I think it might be the "sodium" or rendering optimization mod.

**Comment by tr7zw** [comment]
Yea, sodium currently doesn't do transparency sorting. this causes a lot of issues in other places too. Reference: https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by surfishs** [comment]
![image](https://github.com/tr7zw/FirstPersonModel/assets/96485650/716afba2-34dd-44ff-8d86-0236e4751305)
The good news is that the problem is not caused by "sodium".
Bad news, I need to continue to find out which mod is causing the problem.

**Comment by surfishs** [comment]
I found the culprit and the problem was caused by "iris", although I didn't do anything with it.
![image](https://github.com/tr7zw/FirstPersonModel/assets/96485650/88c94361-44d0-4540-b584-e28f7d25e2fd)

**Comment by tr7zw** [comment]
Yea, Iris modifies a bit how the Sodium pipeline works. I guess for now either leave the pants 2d(might work), don't have the transparent pixels in there, or maybe try if having some shader turned on fixes it? But yea, transparency in Minecraft is a mess, and as long as Sodium+Iris are not done fully implementing the translucent sorting, stuff like this is kinda not preventable.

**Comment by surfishs** [comment]
![image](https://github.com/tr7zw/FirstPersonModel/assets/96485650/ae46adad-500b-406c-8c95-4a2ec0b8833c)
The shader can't modify it in any effective way, and I don't think it's right to "make the feet smaller if the shoe doesn't fit". I think this problem should be solved by iris, but as you can see, modifying Minecraft's rendering engine is an unappealing and uncomfortable thing to do.

**Comment by tr7zw** [comment]
Closing this as translucent sort is nothing I can do about.
