### ISSUE TITLE
Ability to disable head Trinket rendering

### ISSUE THREAD

**Issue by Rafii2198** [tr7zw/FirstPersonModel#362]
From what I see, your helmet is not rendering while you are in first person, I tried some wacky helmets and couldn't see them at all which is good because they don't obscure the screen like Trinkets, just look at this
![image](https://github.com/tr7zw/FirstPersonModel/assets/26695327/035a49f0-1e8e-497b-9988-5c347fca0a74)
I think they shouldn't render too, just like helmets.
For the record, Trinkets do not have hiding ability like Curios, so the only possibility now is taking your Trinkets off or toggling off the mod.

**Comment by JayTsu7** [comment]
Ive also had this issue with the new armour trims, only the trim part loads but i think its the same issue as yours.
![2023-06-13_19 08 20](https://github.com/tr7zw/FirstPersonModel/assets/136169486/54fb66dc-ca5a-44ca-9749-e425ca4dcd41)

**Comment by tr7zw** [comment]
Trinkets are not supported really(too many different mods, implementations, and not much I can do from my end). Armor trims might be unrelated(unless it's inside some custom slot like trinkets).

**Comment by JayTsu7** [comment]
Ah, I'll have a look around to see if its something else then. If it still does it while its the only mod ill let you know.

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/d319cecf-6976-45af-b288-6643c7a434b4)
Gave it a quick shot, armor trims work as expected.

**Comment by JayTsu7** [comment]
Ah lil bit late but the mod causing the bug was FastAnim everything is fine now
