### ISSUE TITLE
forge 1.19.2

### ISSUE THREAD

**Issue by FanRenLa** [tr7zw/FirstPersonModel#363]
![image](https://github.com/tr7zw/FirstPersonModel/assets/83486178/b105fe36-e260-43ed-ae75-da6c1c476c19)

**Comment by tr7zw** [comment]
I mean yea, it's an old number. But it doesn't do anything anyway in this case?

**Comment by FanRenLa** [comment]
> 我的意思是，是的，这是一个旧数字。但在这种情况下，它无论如何都无济于事？

Excuse me, I think there might be some other datapack error.

**Comment by tr7zw** [comment]
Send in the error, I can take a look on what might cause it. This mod doesn't use datapacks/resource pack for any ingame textures, so it's probably something else. Forge just enforces to add this file for some reason.

**Comment by FanRenLa** [comment]
> Send in the error, I can take a look on what might cause it. This mod doesn't use datapacks/resource pack for any ingame textures, so it's probably something else. Forge just enforces to add this file for some reason.

(idasconfig datapack)
I think I may have made some mistakes in editing.

Thank you for your contributions.
