### ISSUE TITLE
Custom models are visible in first person

### ISSUE THREAD

**Issue by Ryhon0** [tr7zw/FirstPersonModel#367]
When an item with a custom model is worn on the head, it is visible in the first person mode
![2023-07-16_19 13 42](https://github.com/tr7zw/FirstPersonModel/assets/21126698/b712bd71-65d1-40bd-81bf-095e58fced8f)

**Comment by tr7zw** [comment]
As far as I know, these are not items in the head slot, but instead using armor stands or so. Nothing I can do about this.

**Comment by Ryhon0** [comment]
That doesn't seem to be the case, I can recreate this on a local server with the following command and resource pack
```
/item replace entity @p armor.head with feather{CustomModelData:1005006}
```
[smpo.zip](https://github.com/tr7zw/FirstPersonModel/files/12064665/smpo.zip)

**Comment by tr7zw** [comment]
Then you have some conflicting mod installed. Head items get hidden correctly:
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/8a472113-7284-4359-9d61-5ecdb064ace8)
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/406bf864-f5f0-415b-b8a1-673099608cbb)
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/2b5d55e2-44a0-476d-8353-756290d990b7)

**Comment by elenawinters** [comment]
> (https://user-images.githubusercontent.com/21126698/253817633-b712bd71-65d1-40bd-81bf-095e58fced8f.png)

The first person view here does not look like First Person Model mod.

**Comment by tr7zw** [comment]
It just has vanilla hands activated.

**Comment by elenawinters** [comment]
Gotcha

**Comment by Ryhon0** [comment]
It seems the [FastAnim](https://modrinth.com/mod/fastanim) mod is making the model visible

**Comment by tr7zw** [comment]
Yea, FastAnime also had conflicts with other mods of mine. I'd suggest only using it when you dont have any mods that try to do stuff with the player model.
