### ISSUE TITLE
Bow is still too close 1.19.2

### ISSUE THREAD

**Issue by phDoenix** [tr7zw/FirstPersonModel#369]
Want to use this mod with Better Combat and otherwise, but considering the bow animation is still in a position blocking the player camera, I can't justify ruining that part of gameplay. Any idea when you'll be backporting the Custom V1 animation from 1.6.4 to proper 1.19.2 versions if at all?

**Comment by tr7zw** [comment]
I really don't get why people insist on using 1.19.2. No one is asking for 1.18.0, so why 1.19.2(or 1.19.3 for that matter)? I may create a new 1.19.2 release next time I work on Not Enough Animations(wrong repo btw), but it's certainly not a priority, 1.19.4/1.20.1 is.

**Comment by sombrae** [comment]
sorry to necro, but to respond ur question; since 1.20 is still relatively new, there's still a lot of mods in 1.19.2 that haven't been ported yet, plus all the 1.19.2 modpacks, and so people keep playing on this version.

**Comment by tr7zw** [comment]
Sorry, but 1.19.2 won't be getting anything new. Also just noticed that this issue is on the wrong mod/git too.

**Comment by tr7zw** [comment]
New branch supports 1.16.5-1.20.4 with the same features.
