### ISSUE TITLE
[Enhancement] Add spectator mode compatibility to mobs from other mods.

### ISSUE THREAD

**Issue by Rocketcat19** [tr7zw/FirstPersonModel#370]
I noticed that in spectator mode, the first-person view of other mod creatures will be blocked by the head models, is it feasible to add compatibility to them?

**Comment by tr7zw** [comment]
The mod tries its best to hide these heads, but if it can't then the mob doesn't define what the head is/the mod can't access it. There is no special logic to make vanilla mobs work, they just use the correct definition.

**Comment by Rocketcat19** [comment]
Does that mean the head can be hidden if the modder uses the correct definition?

**Comment by tr7zw** [comment]
https://github.com/tr7zw/FirstPersonModel/blob/fef8b8286039a6fa6263798699e55351c8ca5c8e/Shared/src/main/java/dev/tr7zw/firstperson/mixins/LivingEntityRendererMixin.java#L30 Basically this is the logic for non "humanoid" models. If the model is a "HeadedModel", then that head gets hidden. That should usually take care of normal mob heads.

**Comment by Rocketcat19** [comment]
I see, probably, thanks.
