### ISSUE TITLE
A very serious problem with hats

### ISSUE THREAD

**Issue by potapenchikov** [tr7zw/FirstPersonModel#373]
Whether it's a modified pumpkin model, with the sodium update to 0.5.0, it began to be displayed in the first person, which completely closes the review. I have observed such a problem with some models before, but as a rule they were models of hats from mods, but vanilla compatibility is completely broken here. I just love this mod and I don't know how to play without it at all))) This is one of the best mods that immerses you in the atmosphere of the game. The developer of this mod is simply the best in his field (with the settings to disable the rendering of arrows in the body, I'm generally delighted) I hope this error will be fixed. To the developer of happiness and good luck in his endeavors, I am very grateful for the existence of this mod

**Comment by potapenchikov** [comment]
Version 1 20 1

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/976f6d15-ddf4-4b9a-9f72-6c5d127dfe51)
Works for me? Probably using some other mod that modifies the player model?

**Comment by potapenchikov** [comment]
modified 3d model pumpkin

**Comment by tr7zw** [comment]
That shouldn't change a thing. In the end, it's just rendering the "Block" on the head. Otherwise, provide some example to reproduce this.

**Comment by tr7zw** [comment]
Closing as stale. In hindside probably related to "FastAnim".
