### ISSUE TITLE
[SUGGESTION] Shaders Compatibility Mode

### ISSUE THREAD

**Issue by JupiterboyLuffy** [tr7zw/FirstPersonModel#378]
With shaders, the body is offset from the shadow your player casts, and I would like to see a toggleable option in the options menu where you can align the body with the shaders shadow
e.g [this](https://imgur.com/a/tYqxpK8)

**Comment by tr7zw** [comment]
Are you perhaps using Optifine or some weird shader? At least historically, the shadow was in the correct place. Also not much I can do about that, I can't move that shadow at all.

**Comment by tr7zw** [comment]
Closing as stale.
