### ISSUE TITLE
Just a little question

### ISSUE THREAD

**Issue by Nihilanthy** [tr7zw/FirstPersonModel#382]
So, there's a way to move the camera in Y axis in the internal config files of the .jar? for me it's looking a little bit too close to the corpse, like my eyes is in the mouth place.

![image](https://github.com/tr7zw/FirstPersonModel/assets/144665486/0cbe97c6-8c41-415c-b461-191630b5a4ef)

**Comment by tr7zw** [comment]
No, this mod does not move the camera at all(neither x/y/z) and has no config to do so.
