### ISSUE TITLE
Content duplication, mod conflict, Carry On.

### ISSUE THREAD

**Issue by al-wei** [tr7zw/FirstPersonModel#384]
Close (First-person Model), repeated visual content appears.

mc version 1.16.5, not sure if there are problems with other mc versions.

on normal
![image](https://github.com/tr7zw/FirstPersonModel/assets/145486869/ef942e34-ccb7-4fc3-bc0b-f805a4089cc3)
off
Repeated the default mc first person Carry On image.
![image](https://github.com/tr7zw/FirstPersonModel/assets/145486869/f14899b3-b604-40f1-8f7c-a8dd1bc0dd5e)

**Comment by al-wei** [comment]
Maybe the Epic Fight was for that reason as well.

**Comment by tr7zw** [comment]
1.16 is entirely unsupported, Epic Fight too. And not 100% sure if it was Carry On(the mod where you can't open the inventory while holding a mob), but it rendered the entire thing so badly, that it won't be possible to get working.
