### ISSUE TITLE
Request : Manual Y offset setting or dynamic to player height

### ISSUE THREAD

**Issue by 1Mercenary** [tr7zw/FirstPersonModel#388]
Using this with origins can leave the camera in some awkward places, as the heights change using Pehkui.

**Comment by tr7zw** [comment]
This mod won't touch the camera, so no Y offsets are planned to be added. Shouldn't Pehkui change the camera height?

**Comment by 1Mercenary** [comment]
Currently testing with Dig's Half Orc Origin. It;s 1.25x and the camera height is inline with the shoulders rather than on top of them.

**Comment by tr7zw** [comment]
I don't know what Origins are, but if a mod changes the player model size, they should probably also change the camera height by the same amount. The only thing I am aware of is that Pehkui's size changes cause the x offset to be off, which requires manually getting them lined up again.

**Comment by tr7zw** [comment]
Closing as its not related to this mod. Camera wont be touched by me, and in return changing the model y makes no sense.
