### ISSUE TITLE
Incompatibility with Alex's Caves maps (1.20.1)

### ISSUE THREAD

**Issue by Vinzound** [tr7zw/FirstPersonModel#392]
This nice mod is not compatible with the cave maps provided the new Alex's Caves mod, both mods are great and I would like the map to be seen like the ones in vanilla Minecraft, I would be happy if had compatibility :)

The character looks green due to an effect from Alex's Caves, it's not a bug or anything like that XD

EXAMPLE:
With First-person Model
![image](https://github.com/tr7zw/FirstPersonModel/assets/144878239/fae9500c-e9c1-4cca-b120-74a4936e4927)

Without First-person Model
![image](https://github.com/tr7zw/FirstPersonModel/assets/144878239/4085680e-c82d-43a2-bf99-f674bb88c667)

**Comment by tr7zw** [comment]
Closing it here as it's not related to this mod.
