### ISSUE TITLE
No Option to Disable the head in First person? Also The Head render Glitch is back

### ISSUE THREAD

**Issue by Red-TF2-Sniper** [tr7zw/FirstPersonModel#398]
Srsly what happened to the option to disable it?
Also this Shit is happening again. Idk whats is really causing this, 
but it maybe due to that im using Forge Version 40.2.0 [debunked]
1.18.2, 104 mods Forge 40.2.0, Running rubidium instead of Optifine
![2023-11-19_15 24 17](https://github.com/tr7zw/FirstPersonModel/assets/91907457/70c41e8f-09b0-457a-ad5a-aa3d8904e171)

**Comment by Red-TF2-Sniper** [comment]
To be Honest, This could be all fixed by adding an option to disable head Rendering in first person. I remember that older First Person Mods used to do this by default.

**Comment by tr7zw** [comment]
You have an incompatible mod installed that probably replaces the player model, that's why the head is there. Mods like Epic fight.

**Comment by Red-TF2-Sniper** [comment]
> You have an incompatible mod installed that probably replaces the player model, that's why the head is there. Mods like Epic fight.

I dont have Epic fight, only Better combat

**Comment by tr7zw** [comment]
Then you have some other mod messing with the player model. 1.18.2 is a bit old so I'm not too sure anymore, but possibly Essential was still incompatible back then.

**Comment by Red-TF2-Sniper** [comment]
Thats not the case either, as i have no use for Essential, tho i just remember that i was forced to update Player Animator from 0.4.2 to 1.0.4 due to a java update

**Comment by tr7zw** [comment]
Player Animator should be fine. I can't guess what other 104 mods you have installed, and neither can I guess which mod might cause this otherwise. Bestcase just remove this mod or figure out which combination is causing the issue.

**Comment by Red-TF2-Sniper** [comment]
Figured it out, It was Timeless and Classics Mod 0.3.10-1.18.2 BETA

Which is surprising to me

**Comment by tr7zw** [comment]
Cant find them, only some Fabric mod that is called Timeless. But from the sound of things they add old features? Maybe they do it kinda badly by replacing the player model with a custom one to play some old animations or something?

**Comment by Red-TF2-Sniper** [comment]
> Cant find them, only some Fabric mod that is called Timeless. But from the sound of things they add old features? Maybe they do it kinda badly by replacing the player model with a custom one to play some old animations or something?

Timeless and Classics is a Gun Mod that Used to be with CGM until they separated and became its own mod. it was for 1.16.5 until now as they added support to 1.18.2
if you want, here is the link to the mod: https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac/files/4867165

**Comment by Red-TF2-Sniper** [comment]
Also ignore the weeb shit, since they also added full support to Yes Steve Model

**Comment by PSYCHEER** [comment]
![image](https://github.com/tr7zw/FirstPersonModel/assets/42911029/3dd6f077-f80f-4c67-beb9-d579ab5e60e9)
in this version it's back!

**Comment by tr7zw** [comment]
> ![image](https://private-user-images.githubusercontent.com/42911029/298168562-3dd6f077-f80f-4c67-beb9-d579ab5e60e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTQzOTksIm5iZiI6MTcwNTY5NDA5OSwicGF0aCI6Ii80MjkxMTAyOS8yOTgxNjg1NjItM2RkNmYwNzctZjgwZi00YzY3LWJlYjktZDU3OWFiNWU2MGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE5NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOGJlN2Q4NmRhYjM0Mjk0MmUxZjM0NTU5ZDc3MzQzMjM4N2RlNWQ4ZDZhNjE2NzcxMWM3MTlhZGQ3M2FjOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aOTJNTYv_ob-W_g2eb8W0hgjLgceTy7XShbslRsZrwM) in this version it's back!

Compared to not being there before(with 2.2.x)? Which mod are we talking about, causing the problem? Not much about the head hiding changed in that release, at least for 1.20.2.

**Comment by PSYCHEER** [comment]
We're talking about FirstPersonModel mod, yesterday I updated it on modrinth, this bug occured on version 2.3.0 on MC1.20.2. On previous version it works, so I know problem would be somewhere here, so I reported it.

**Comment by tr7zw** [comment]
> We're talking about FirstPersonModel mod

Read the messages above on this thread. This happens when you have an incompatible mod installed with it. So my question is: which incompatible mod do you have?

**Comment by PSYCHEER** [comment]
I read it, but problem is, I have not any incompatible mod, I checked all mods which can be incompatible but nothing found. I have Not Enough Animations and 3D skin layers, but no of that is doing this shit... So IDK, that's why I found this issue thread, question persist. Why in 2.2.4 on 1.20.2 it works, and on 2.3.0 it not.... and updated was just FPM

**Comment by PSYCHEER** [comment]
And another mods I have are just rendering things like sodium, starlight, ferritecore etc... I have not any other mods, then just hud and chat mods...

**Comment by tr7zw** [comment]
> I read it, but problem is, I have not any incompatible mod, I checked all mods which can be incompatible but nothing found. I have Not Enough Animations and 3D skin layers, but no of that is doing this shit... So IDK, that's why I found this issue thread, question persist. Why in 2.2.4 on 1.20.2 it works, and on 2.3.0 it not.... and updated was just FPM

Well, I developed Not Enough Animations and 3D skin layers, so that's not it. Mods like FastAnim or EpicFight cause issues like this. Otherwise, send the full modlist(worstcase screenshot the mods folder) so I can take a look.

**Comment by PSYCHEER** [comment]
FastAnim was the cause, I didn't though about that one, totally forgot about it
