### ISSUE TITLE
Minecraft shuts down as soon as I start a world

### ISSUE THREAD

**Issue by Yxhx48** [tr7zw/FirstPersonModel#400]
I'm trying to play first-person model with optifine but it keeps shutting down as soon as I start a world, I read about the incompatibility with the optifine emissive textures but is there a way to play with it or nothing at all?

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/835fa2c6-38b7-4528-b209-42912479a92b)
Works absolutely fine with optifine.

**Comment by tr7zw** [comment]
Stale
