### ISSUE TITLE
Treasure Maps turn into normal maps when opened.

### ISSUE THREAD

**Issue by CROdator** [tr7zw/FirstPersonModel#402]
As the title says, when u use this mod and try to look at a treasure map that you find in sunken ships the map just turns into normal map, making you unable to find the treasure.

**Comment by CROdator** [comment]
found third treasure map and this one worked normaly

**Comment by tr7zw** [comment]
Treasure maps are just normal maps as far as the game is concerned(and Not Enough Animations, where this issue would be correctly located).
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/bdab7dba-13ae-4d25-8fff-49f9eb405c2e)
Also works just fine from my testing. Did you check that the maps work in the vanilla first person?

**Comment by CROdator** [comment]
> Treasure maps are just normal maps as far as the game is concerned(and Not Enough Animations, where this issue would be correctly located). ![grafik](https://private-user-images.githubusercontent.com/5133936/297459354-bdab7dba-13ae-4d25-8fff-49f9eb405c2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzcxODIsIm5iZiI6MTcxMjkzNjg4MiwicGF0aCI6Ii81MTMzOTM2LzI5NzQ1OTM1NC1iZGFiN2RiYS0xM2FlLTRkMjUtOGZmZi00OWY5ZWI0MDVjMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTU0ODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE3M2U5MDU4NWQ3MTRkMjYyNzNlODJlOGU5YTJhZTFkYTljNzZlNTgzYzhhMmMxZTliNWUyYzcyZDAxOGRmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5PxUQuu24PxvgWrWN8fwmVIaqIqHzvA0I2aNlBtTDmk) Also works just fine from my testing. Did you check that the maps work in the vanilla first person?

Sorry for abandoning thread, ive stopped playing for a while. Now again when playing on vanilla server it happened again. Maps work normally without the mod but if i pick up a buried treasure map while the mod is enabled they are named Buried treasure map but they look like empty map and if i use mouse click then it just changes the map into a normal map.

**Comment by tr7zw** [comment]
> > Treasure maps are just normal maps as far as the game is concerned(and Not Enough Animations, where this issue would be correctly located). ![grafik](https://private-user-images.githubusercontent.com/5133936/297459354-bdab7dba-13ae-4d25-8fff-49f9eb405c2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzcxODIsIm5iZiI6MTcxMjkzNjg4MiwicGF0aCI6Ii81MTMzOTM2LzI5NzQ1OTM1NC1iZGFiN2RiYS0xM2FlLTRkMjUtOGZmZi00OWY5ZWI0MDVjMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTU0ODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE3M2U5MDU4NWQ3MTRkMjYyNzNlODJlOGU5YTJhZTFkYTljNzZlNTgzYzhhMmMxZTliNWUyYzcyZDAxOGRmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5PxUQuu24PxvgWrWN8fwmVIaqIqHzvA0I2aNlBtTDmk) Also works just fine from my testing. Did you check that the maps work in the vanilla first person?
> 
> Sorry for abandoning thread, ive stopped playing for a while. Now again when playing on vanilla server it happened again. Maps work normally without the mod but if i pick up a buried treasure map while the mod is enabled they are named Buried treasure map but they look like empty map and if i use mouse click then it just changes the map into a normal map. Even if i pickup the buried treasure map, change into normal view it will still be the same, i have to disable the mod entirely, pick it up and then enable the mod for it to show normaly.

The mod is clientside and just visual. It can't change behavior like what items do. And as seen from the pic, I wasn't able to replicate it. I found a shipwreck, opened the chest, picked up the map and it worked just fine.
