### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by kittenvr** [tr7zw/FirstPersonModel#405]
Could you port this mod to 1.20.4

**Comment by ancap-kun** [comment]
1.20.2 version works for me on 1.20.4

**Comment by itsaerosphere** [comment]
Prism Launcher won't let me launch Minecraft with the 1.20.2 version of the mod. Please update to 1.20.4

**Comment by tr7zw** [comment]
It's in the dev version, release once I get to check all 65 open issues on what can be quickly fixed/added rn.
