### ISSUE TITLE
When I look down in swim,cloak will occlude the view.

### ISSUE THREAD

**Issue by pengtao6993** [tr7zw/FirstPersonModel#409]
When I look down in swim,cloak will occlude the view.It looks like these:
![2024-01-10_17 51 02](https://github.com/tr7zw/FirstPersonModel/assets/98449551/d5c67b57-7cb0-4d0f-823e-349a558f0506)
![2024-01-10_17 51 19](https://github.com/tr7zw/FirstPersonModel/assets/98449551/6ab0f304-22da-4b6e-bbc3-35d51a55af31)
Game Version:Minecraft 1.20.1 with fabric 0.14.21,fabric api 0.83.1,sodium 0.53 and iris 1.6.10
Shaders:Iris Shaders 1.6.10 with Sildur's Vibrant Shader v1.50 High

**Comment by tr7zw** [comment]
Aware, its probably with WaveyCapes too? Anyway, going to rework the swimming logic at some point or at least disable the cape.
