### ISSUE TITLE
Incompatible with essential's cosmetics

### ISSUE THREAD

**Issue by dima-dencep** [tr7zw/FirstPersonModel#411]
![image](https://github.com/tr7zw/FirstPersonModel/assets/66722732/81982ef0-d0cf-43ef-88dc-4c3cd5ae087c)
The cat on my head gets in the way and covers half the screen, I can't remove it because I clearly spent money on it

**Comment by tr7zw** [comment]
Can you confirm that you don't have FastAnim installed? Essentials should be fully compatible.

**Comment by tr7zw** [comment]
Closing as probably invalid due to FastAnim.
