### ISSUE TITLE
Torso becomes invisible in 3rd person while swimming

### ISSUE THREAD

**Issue by Aster-sama** [tr7zw/FirstPersonModel#412]
Version is 1.20.4, also happens in 1.20.2. No other mods other than Fabric API are loaded. 
FirstPerson 2.3.0, Fabric Loader 0.15.6, Fabric API 0.95.0.
![image](https://github.com/tr7zw/FirstPersonModel/assets/36829052/ec813fcb-1bd7-40df-a3d2-9863733ec9bb)

https://github.com/tr7zw/FirstPersonModel/assets/36829052/26abfa8f-ea1c-44e4-a11c-41de3607553d

Torso reappears when stop swimming

**Comment by healbrat** [comment]
Same here. Downgrading to version 2.2.4 for 1.20.1 fixes the issue.

**Comment by tr7zw** [comment]
That has already been fixed in the dev version.
