### ISSUE TITLE
Application for Exposure mod support

### ISSUE THREAD

**Issue by WelkinDEX** [tr7zw/FirstPersonModel#414]
![2024-01-25_15 09 43](https://github.com/tr7zw/FirstPersonModel/assets/106245582/8af301ab-6ba4-4f21-9608-f3a4d649c57b)
When I use the camera from Exposure mod, the first-person hand blocks the lens. Could u add like Auto Vanilla Hands for this mod, plz :3

**Comment by tr7zw** [comment]
It's in the config file, anyone can add it there. Please provide the item ids.

**Comment by WelkinDEX** [comment]
It’s "exposure:camera", 
But I found it a bit odd that you can see the body whether the camera is in use or not. Maybe you can add an Auto Toggle Firstperson? Like use the First-person Model when you are not using the camera but holding it, and use the Vanilla First-person when you are using the camera. Is that possible?
![2024-01-27_12 33 51](https://github.com/tr7zw/FirstPersonModel/assets/106245582/8a200c7c-245c-4c26-82e8-dec27f3ff26e)
![2024-01-27_12 34 05](https://github.com/tr7zw/FirstPersonModel/assets/106245582/4edca985-fe54-4480-aa0a-3536068fccb0)

> It's in the config file, anyone can add it there. Please provide the item ids.

**Comment by tr7zw** [comment]
Hm. Then it would be a case for #408 . I guess I'll have to add that.
