### ISSUE TITLE
Crash with Better Combat

### ISSUE THREAD

**Issue by mpustovoi** [tr7zw/FirstPersonModel#417]
After updating to version **2.3.1** of First-person Model and trying to hit a mob my game crashed.
Version **2.3.0** worked fine.
Details:
• Fabric Loader — **0.15.6**
• Fabric — **1.20.1**
• Fabric API — **0.91.0+1.20.1**
• First-person Model — **2.3.1-1.20.1 - Fabric**
• Better Combat — **1.8.3+1.20.1**
• playerAnimator — **1.0.2-rc1+1.20-fabric**

Crash report and latest.log:
https://gist.github.com/mpustovoi/b7bc2ed04ebfe1b93f3fe725946bf384

**Comment by tr7zw** [comment]
Better Combat will have to update, it's not using the API but instead calling into internals. For the dev version I re-added the field its trying to get as a workaround against the crash.
