### ISSUE TITLE
Incompatibility with Better Combat mod

### ISSUE THREAD

**Issue by damikdevil** [tr7zw/FirstPersonModel#420]
[latest.log](https://github.com/tr7zw/FirstPersonModel/files/14073084/latest.log)
[crash-2024-01-27_22.46.48-client.txt](https://github.com/tr7zw/FirstPersonModel/files/14073085/crash-2024-01-27_22.46.48-client.txt)

**Comment by tr7zw** [comment]
Duplicate #419
