### ISSUE TITLE
Suggestion - Old 1.16.5 head rotation and more compatibility options

### ISSUE THREAD

**Issue by niconekozilla** [tr7zw/FirstPersonModel#421]
Hi, I love this mod and I play on 1.16.5. I´m very grateful for you still updating for 1.16.5, but there´s one thing that I don´t like that much; when you rotate your body goes to the sides and it looks off. The way it was in the old 1.16.5 version was perfet in my opinion. May it be too much to ask for an option to use that old head rotation with all the new improvements?.
 
 Other thing is that by giving me the possibility to disable the model with certain items, you made it so much better for me to use this mod along side epicfight, as I always had to use 3rd person for when I enter combat mode, I made a datapack that puts me in mine or battle mode depending on the item I have in hand, because epicfight has a command for forcing players into modes I was able to do that and it will be just as good to have a similar command for enabling/disabling the first person model.
Thank you for your work, I really appreciate that you still working and supporting 1.16.5, and sorry for my bad english :)

**Comment by tr7zw** [comment]
> much; when you rotate your body goes to the sides and it looks off.

You have body locking turned on in Not Enough Animations.

> Other thing is that by giving me the possibility to disable the model with certain items,

Was just added in 2.3.2.

**Comment by niconekozilla** [comment]
About the model disabling; I´m talking about a console command like, something like: "/firstpersonmodel displaymodel true/false" it may be useful but it´s just a little suggestion.
About the rotation; I don´t activate that option because I like more the one that keeps the body facing the ladders. Maybe I didn´t chose the correct words, what I was trying to point is this please look:
![2024-01-28_16 17 04](https://github.com/tr7zw/FirstPersonModel/assets/139291445/67b4a548-cea4-44cf-80ef-928ab2afb6ce) the head looks disjointed even having the offset on 0, having it on 20 or 40 looks even worst because of the body going to the side.
![2024-01-28_16 20 17](https://github.com/tr7zw/FirstPersonModel/assets/139291445/c0e10f8f-ae79-478a-9b86-34d856dc49b2)on the old buid it was just fine in 0, I ussually like to use it in 20
![2024-01-28_16 20 44](https://github.com/tr7zw/FirstPersonModel/assets/139291445/144a5970-7347-4411-8b50-cd684a970775) having it in 40 looks the same as the epicfight first person so I would like to have it to look like this again.
Also may be that it is a bug or something only I have wrong so please tell me. Thank you :)

**Comment by tr7zw** [comment]
I'll be quite honest, I don't understand either thing you mean. Maybe join the discord so we can better talk about it.
> the head looks disjointed even having the offset on 0, having it on 20 or 40 looks even worst because of the body going to the side.

Do you maybe mean the old bug where the offset used the body instead of the head(or the other way around, don't remember). This was fixed/changed about 2 years ago, 1.16.5 just never got the update. The issue with that is, that the body just slides all over the place, looking really awkward. There is no way to fix that, since the player camera rotates on a single point, while the head logically moves around while rotating. Either it slides, or it looks a tiny bit illogical. I choose the latter. 

> About the model disabling; I´m talking about a console command like, something like: "/firstpersonmodel displaymodel true/false" it may be useful but it´s just a little suggestion.

I don't get it. Do you mean the f6 toggle key that's built in? Or the config value to auto toggle off the mod when holding certain items. What would that command even do? And why a command?

**Comment by niconekozilla** [comment]
Oh it was a bug, I understand. 
I was talking about a command that works just like the toggle key, but usable in datapacks and that stuff, but I understad that it is very situational and that there is already a new config for that so please do not worry about it. Thank you :)

**Comment by tr7zw** [comment]
> I made a datapack that puts me in mine or battle mode depending on the item I have in hand

Basically just add the items to the list of items that auto toggle off the mod, and that's it :D 

And yea, it was a bug that I used I think the head rotation to calculate the offset. So when you looked down and then left/right the entire body just slides around.
