### ISSUE TITLE
Armor status flashing while in First Person mode

### ISSUE THREAD

**Issue by Anonyku05** [tr7zw/FirstPersonModel#422]
The armor status (next to the food bar) is flashing in first person mod, look in record

https://github.com/tr7zw/FirstPersonModel/assets/48128391/87c3e272-fd95-44d1-b97b-607a148b1bce

**Comment by tr7zw** [comment]
Am somewhat able to replicate it. It's weird since that would mean the UI gets rendered while the player gets rendered which is never the case. Will have to look into it.
