### ISSUE TITLE
Advertise quilt support on modrinth

### ISSUE THREAD

**Issue by CuteistCat** [tr7zw/FirstPersonModel#425]
Title describes it. Works with quilt, advertiseing quilt supports adds auto updateing on thesus(modrinth launcher) and lets you add it without "overiding loaders" on thesus

**Comment by tr7zw** [comment]
I don't test with Quilt, thats why I don't add the tag. Quilt users have to test themselves, but usually, all Fabric mods should work.

**Comment by CuteistCat** [comment]
i recomend adding it just to indicate that issues involving quilt will be fixed and quilt is supported

**Comment by CuteistCat** [comment]
(and add it to any other of ur mods that will have quilt-only bugs fixed

**Comment by tr7zw** [comment]
> i recomend adding it just to indicate that issues involving quilt will be fixed and quilt is supported

> I don't test with Quilt, thats why I don't add the tag.

Thats the exact point. Quilt is not supported and issues won't be fixed as it's Quilt issues, not Fabric.
