### ISSUE TITLE
Incompatability with Mr. Crayfish's Gun Mod

### ISSUE THREAD

**Issue by Keoni2008** [tr7zw/FirstPersonModel#426]
When using the First-person Model mod with Mr. Crayfish's Gun Mod the scopes of the guns are off of the screen to where the scopes are unusable.  My version is 1.19.2 for all the mods

**Comment by tr7zw** [comment]
Duplicate #357 #302 #266. Add them to the vanilla hands config list or auto toggle list.

**Comment by tr7zw** [comment]
Also thats the 3rd person animation. There is nothing I could do to line them up, as it's not my mod.

**Comment by Keoni2008** [comment]
Ok, thanks!
