### ISSUE TITLE
Bow item is still gargantuan on 1.20.1

### ISSUE THREAD

**Issue by Barerock** [tr7zw/FirstPersonModel#429]
Your sideways bow animation essentially fixed the problem, but it is no longer a solution from what I can tell. Aptly described as a mod-breaking issue.

**Comment by tr7zw** [comment]
> but it is no longer a solution from what I can tell.

What do you mean?

**Comment by Barerock** [comment]
This is similar if not identical in nature to all previous posts featuring the bow items. They're unusable due to angle, which you solved by making a temporary sideways bow animation which was sick af, but sadly doesn't seem to be available for 1.20.+.

**Comment by tr7zw** [comment]
The alternative animation is part of "Not Enough Animations"(basically required to use this mod). Then the bow is held sideways and lower, so it doesn't block the camera.

**Comment by tr7zw** [comment]
> a temporary sideways bow animation which was sick af, but sadly doesn't seem to be available for 1.20.+.

This has been ported to 1.16.5-1.20.4? It's available on all versions.

**Comment by Barerock** [comment]
Is it ported as a separate mod? I haven't been able to find it. I think curseforge/modrinth have been burying relevant results poorly sometimes.

**Comment by tr7zw** [comment]
It has been on Not Enough Animations the entire time and is also turned on by default when you do a fresh install of Firstperson Mod with NEA.

**Comment by tr7zw** [comment]
Just go into the settings and turn it on. (Of Not Enough Animations, not Firstperson Mod)

**Comment by Barerock** [comment]
Hm. Bow animation is definitely not sideways, it puts the bowstave directly in my eyeball lol. Definitely not on by default, but thank you for directing my ignorance. You're as helpful as always.

To be fair to myself, Configured is dogwater now for whatever reason. It can't find related configs at all. Had to switch to an unfamiliar one by MrCrayFish, so I probably skipped over the config before I switched.

**Comment by tr7zw** [comment]
"Configured" never heard of that and its not supported(at least from my end). https://modrinth.com/mod/modmenu ModMenu on Fabric and the built-in one for Forge/NeoForge are the supported config styles.

**Comment by Barerock** [comment]
Configured is pasted in lots of descriptions as the go to. Used it before with little issue. MCF one is actually really good, I suggest a poke.

I HAD NEA DISABLED. Maaaaaaaan.

**Comment by Barerock** [comment]
"It's all user error." My dad.

**Comment by tr7zw** [comment]
🙃
