### ISSUE TITLE
Can't use maps, default icon shown instead

### ISSUE THREAD

**Issue by DarkblooM-IO** [tr7zw/FirstPersonModel#432]
Easiest workaround is to enable "use vanilla hands"

![image](https://github.com/tr7zw/FirstPersonModel/assets/54911078/f7af8d1e-a21a-48f1-8680-077df9ce16ef)

**Comment by Deepfriedyag** [comment]
where is this mods' config I can't see it? Using the forge version on 1.16.5

**Comment by tr7zw** [comment]
You forgot to install NotEnoughAnimations, the required dependency.

**Comment by tr7zw** [comment]
Then it's not a vanilla map?
