### ISSUE TITLE
Request to (optinal) Remove only left or only right arm.

### ISSUE THREAD

**Issue by downloders** [tr7zw/FirstPersonModel#434]
Application for adding an additional feature to the mod settings
and why is this needed?

for the sake of compatibility with other **(animation)** mods.

(If this can be **done** then **write** to **me!)**

**Comment by tr7zw** [comment]
How would only removing one arm during vanilla hands make it more compatible with other animation mods?

**Comment by downloders** [comment]
Compatible with animation mods oh wait i will send screen shot
![изображение_2024-03-22_192519392](https://github.com/tr7zw/FirstPersonModel/assets/162686805/1018f331-0fe0-4855-a205-a2bb5cdba1be)
and
![image](https://github.com/tr7zw/FirstPersonModel/assets/162686805/903cb0c0-4887-4c69-8b0b-5b9b9e0549c3)

**Comment by tr7zw** [comment]
That looks like you didn't turn on Vanilla Hands in the settings.

**Comment by downloders** [comment]
Withot Vanilla Hands
![image](https://github.com/tr7zw/FirstPersonModel/assets/162686805/62fc828d-b28f-42cf-b1e4-9f5b2761f95a)
with Vanilla Hands(look at the shadow i hold shield but this not visible)
![image](https://github.com/tr7zw/FirstPersonModel/assets/162686805/10221610-db52-48dd-a610-6bd61fd901c1)
Here with Vanilla Hands with double hands
![image](https://github.com/tr7zw/FirstPersonModel/assets/162686805/56a0ab1d-597c-4419-b188-7ed1a4bdb0cd)

**Comment by downloders** [comment]
and yeah sorry for destrubing😥

**Comment by tr7zw** [comment]
Not sure why the shield wouldnt be visible. You can try the latest dev build, but otherwise this is just a plain incompatibility with whatever mod you are using there(looks like what I was working on but stopped because trainguy was also working on this).

**Comment by downloders** [comment]
i download working from (github) not discord server mod. 
i can't find they server Unfortunately.

**Comment by downloders** [comment]
That link on github invalid

**Comment by downloders** [comment]
So sorry for bothering you, I'll probably find another animation mod :)

**Comment by tr7zw** [comment]
As I said, I used to work on exactly this(seeing the arm in firstperson https://github.com/tr7zw/AnimatedFirstPerson), but since trainguy is working on the same thing but better, I stopped.

**Comment by downloders** [comment]
I think about all that and i can say trainguy abodoned they mod on github but continue update in discord.
                                               i try download your mod through gradlew build 
                                                     (i know that mod can't be downloaded)
                                                   but i still wants see full body from first person
                                                            and maybe you have some ideas..
                                                          (becuse about i think are too complex)
                                               (and yes I'm sorry i have porly level of speaking on english)
                                                                            (don't mind :) )

**Comment by downloders** [comment]
wrote a lot of cringe ngl.

**Comment by downloders** [comment]
see you tomorow!

**Comment by downloders** [comment]
Can I modify your mod?

**Comment by downloders** [comment]
Can i download that?

**Comment by tr7zw** [comment]
It's stuck on 1.19.2 or so and incomplete as I never finished that mod.

**Comment by downloders** [comment]
les'go i started that!
that pretty cool that i can say

**Comment by tr7zw** [comment]
Gonna close this. Once Trainguy finishes his mod, then it's time to look into that.
