### ISSUE TITLE
An option to hide item on offhand when pulling bow

### ISSUE THREAD

**Issue by BakinDP** [tr7zw/FirstPersonModel#436]
Would be a nice addition to hide item in offhand when pulling bow, since there are a plenty 3D RPs/Player animation mods, that may cause blockage of view.
![2024-03-13_18 39 18](https://github.com/tr7zw/FirstPersonModel/assets/74774853/db6f45fb-f155-4761-951b-9791d9e96931)

Thanks!

**Comment by YoungSoulluoS** [comment]
Hi,
you can try this mod, it's compatible & resolve this problem https://modrinth.com/mod/not-enough-animations

**Comment by BakinDP** [comment]
I'll try this out, I appreciate it!

**Comment by tr7zw** [comment]
Yea, NEA does that and its a required mod in general for this mod.
