### ISSUE TITLE
Unable to see the body while swimming in the third person. 

### ISSUE THREAD

**Issue by Rocketcat19** [tr7zw/FirstPersonModel#439]
![56](https://github.com/tr7zw/FirstPersonModel/assets/113609599/c3e59099-369e-46b7-8e32-c2b266f3af05)

**Comment by tr7zw** [comment]
Update the mod, this has been fixed 2 months ago https://github.com/tr7zw/FirstPersonModel/commit/3be55a3b05929502dcec1766e7c0215d0f5256fb .
