### ISSUE TITLE
Arms dissapearing / stops rendering

### ISSUE THREAD

**Issue by Zouzs** [tr7zw/FirstPersonModel#440]
https://github.com/tr7zw/FirstPersonModel/assets/44651203/60e96bca-8102-4276-9a86-227d2e1aff31

Quilt 0.23.1 - 1.20.1
Mod v2.3.4

Weird interaction when holding a camera from Exposure mod and a bow from Archers mod in the left hand (Just the one that changes the holding to two hands.)

The arms are not recovered by exiting and leaving the world, not even restarting the whole game, only turning the mod off, opening the game, closing it, and opening it again with the mod back on.

I suspect it has to be something with having two items that changes the way the holding works, it also happens with Map Atlases (Not needing to have another item, just by holding it in the off-hand.)

**Comment by GitJason33** [comment]
yes when you hold map atlas in hand, the hands both disappear. i tried to troubleshoot the problem, your hands come back if you turn on then off vanilla hands in configs. thats not practical if this always happens when you hold the atlas (or any other item that makes same error)
