### ISSUE TITLE
In the Forge version, see Vanilla hands.

### ISSUE THREAD

**Issue by DetectivWolf** [tr7zw/FirstPersonModel#446]
So, I got a problem. I'm trying to see my Vanilla Minecraft hands but, I'm unable to see the option. Is this a only Fabric feature?

**Comment by DetectivWolf** [comment]
If anyone has the same problem, I found a way. Open your Minecraft laucher, go to your prefered version, press on the file icon. Go to the file cofing, and in the file there should be a first person file that'll be a .JSON. In the file, they'll be a "Vanilla hands" option. Make it ot "true".

**Comment by tr7zw** [comment]
The Forge version is 1:1 the same as Fabric(just compiled for Forge). Its in the settings menu with all other options. No need to edit the json for that.
