### ISSUE TITLE
Incompatibility with Sodium

### ISSUE THREAD

**Issue by peow** [tr7zw/FirstPersonModel#447]
I added the Crossbow to AutoVanillaHands, and when I open the game using Sodium, when I hold the Crossbow I am transformed into an Among Us
![2024-05-12_22 53 15](https://github.com/tr7zw/FirstPersonModel/assets/105888751/f604e198-201a-40ff-b8d5-f983726ce850)
![2024-05-12_22 53 23](https://github.com/tr7zw/FirstPersonModel/assets/105888751/f3607760-4a7b-4b9c-8628-efeeb2c08272)

*since Minecraft doesn't refresh a model while you're viewing the model, you need to exit F5 and come back*

the arms of the skin disappear and do not return even after I am no longer holding the Crossbow

![2024-05-12_22 54 09](https://github.com/tr7zw/FirstPersonModel/assets/105888751/ed6c2483-09ac-453e-9c1f-6889abf380da)
![2024-05-12_22 56 08](https://github.com/tr7zw/FirstPersonModel/assets/105888751/603666c9-9947-4c6a-8121-920d4acd63d1)

and this is only fixed by restarting the game

-------------

im only using this mods: 
![2024-05-12_22 55 19](https://github.com/tr7zw/FirstPersonModel/assets/105888751/2a6c8637-f5df-48f2-bee8-efe5942d7b06)

Fabric 1.20.1
First-Person Model 2.3.4
Sodium 0.5.8

------------

firstperson.json: https://gist.github.com/peow/9169bba9a8ad7f3250924d55d6d2add8

latest.log: https://gist.github.com/peow/2cfa48d82fb53c3ef3b3681422663da5

if is possible to fix this pls make an update to Fabric **1.20.1**, thanks

**Comment by PiniponSelvagem** [comment]
Fabric 1.20.6
First-Person Model 2.4.1
Sodium 0.5.8

Same problem, no vanilla hands. In dynamic mode they show, but not when set to always show and dynamic off.

**Comment by tr7zw** [comment]
> Same problem, no vanilla hands. In dynamic mode they show, but not when set to always show and dynamic off.
Edit: My issue is not related to the crossbow, but with any item, even bare hands. Vanilla hands never show.

Soooo its an entirely different issue/question?

**Comment by PiniponSelvagem** [comment]
> > Same problem, no vanilla hands. In dynamic mode they show, but not when set to always show and dynamic off.
> > Edit: My issue is not related to the crossbow, but with any item, even bare hands. Vanilla hands never show.
> 
> Soooo its an entirely different issue/question?

Im not sure, thats why I only commented.
Seems related to me.
In discord i created an issue in the “mod-support”, since i didnt found any related there, “[1.20.6] No hands with Sodium”.
I can also create the issue here, if thats better.
