### ISSUE TITLE
incompatibility with Elytra Trims

### ISSUE THREAD

**Issue by peow** [tr7zw/FirstPersonModel#448]
when using the Elytra Trims together with the First-Person Model, when holding an Elytra in your hand the head of your skin disappears *(with this mod Elytra gets a 3D model in the inventory)*

![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/d08c340c-6992-4f70-86ea-d28de31621ea)
![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/351f5b0f-7f32-4640-8b6b-b42bde04d6ba)

*since Minecraft doesn't refresh a model while you're viewing the model, you need to exit F5 and come back to see that your head is gone*

--------------------

First-Person Model usually disables the rendering of some part of the body when it detects that this will hinder the first-person view, I imagine that something in the Elytra Trims has made First-Person Model think that the Elytra in the hand would be equipped in the head or something similar, idk

the problem stops when you press F6 to disable First-Person Model, or you disable the "Use Elytra Model" option
![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/8cf5bc9e-9e24-499f-ae8a-d1c25a5012e7)

I showed this problem to the developer of Elytra Trims and he said:
"**but on a serious note i don't know. It also can make your head reappear in 3rd person just as magically and the mods don't have any code interacting with each other.**"

https://github.com/kikugie/elytra-trims/issues/58

----------

I'm using Fabric 1.20.1, First-Person Model 2.3.4, Elytra Trims 3.1.5
![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/fbc6db52-7d64-4706-bf22-b95fa48b4b4b)

mod link: https://modrinth.com/mod/elytra-trims

if is possible to fix this pls make an update to Fabric **1.20.1**, thanks

**Comment by kikugie** [comment]
For reference I referenced the technical details on the FPM discord: https://discord.com/channels/342814924310970398/1239494282742730773
