### ISSUE TITLE
Arms disappear in Multiplayer

### ISSUE THREAD

**Issue by Insane96** [tr7zw/FirstPersonModel#450]
Forge 47.2.30
FPM: 2.4.0-1.20.1

In multiplayer if you set Vanilla Arms to Always (With dynamic off), most of the players will lose the arms
Will test ASAP without performance mods

![2024-05-19_20 40 22](https://github.com/tr7zw/FirstPersonModel/assets/7185104/dcaa17cd-b2a5-41aa-8f01-9b4c18197a89)
![2024-05-19_20 40 03](https://github.com/tr7zw/FirstPersonModel/assets/7185104/296dde98-a80a-4c84-9d58-e83b8354b64e)

**Comment by tr7zw** [comment]
Duplicate #440
