### ISSUE TITLE
request: removal of the “Enabled by Default” option

### ISSUE THREAD

**Issue by peow** [tr7zw/FirstPersonModel#452]
![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/e182c0bb-9848-42ad-b82a-6e4b3a354437)

I can't see the point of this option, I think the mod should just follow the last state in which the user left Firstperson, if disabled when opening the game again it will remain disabled, if enabled it remains enabled 
*(and when opening the game for the first time it would obviously be enabled)*

As with the Iris mod, for example, in the mod's settings there is a line that defines whether the shaders are active or not.

![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/8010b91d-6fde-4f2e-a274-169ec3a17c31)

----------------

a hypothetical situation could be where the FirstPerson-Model is in a modpack, and a random user doesn't like to see their model in the first-person view, but this user is a layman and doesn't understand about ModMenu and mod configuration, they just downloaded it and are playing, they will see the hotkey (F6) saying about toggling the mod, and they will have to use it every time they reopen the game, which would piss him off
![image](https://github.com/tr7zw/FirstPersonModel/assets/105888751/ec1693d4-dea7-4325-8f32-7bdafcb1ae93)

if you agree to this change I ask for an update to 1.20.1, thanks for reading

**Comment by tr7zw** [comment]
I don't really get the point. This option is there for people that want the mod off by default, turning it on only for certain gameplay parts. Saving the on/off state of the hotkey would require a bunch of logic to not cause lag and would just cause confusion("HELP, suddenly the mod turned off and no matter what I do, even after a restart it's not fixed?!?" after accidentally pressing f6). And same with modpacks, where you want to give people the option to use the mod, but don't force them by default.

**Comment by tr7zw** [comment]
> hmmmm, I don't understand why, isn't it just storing the state in the configuration file?

that would cause a lag spike

>  just like the Iris mod does, does Iris

You don't switch shaders on/off all the time and there is a lagspike when you do with the hotkey. No clue if they do the saving in the background.

> but the opposite can also happen, where people don't understand why the mod keeps deactivating itself when they reopen the game.

It's on by default, so less likely people turn open the setting and turn it off by accident.

> A Toast notification could also be added when the hotkey is pressed for the first time

All of that assumes people know about the hotkey. People more likely know how to access settings, than to check the hotkey screen for a hotkey they don't even know about. 

Tbh, I really don't get the point of this issue. Why remove a feature just because it doesn't apply to you?

**Comment by tr7zw** [comment]
> I was imagining a modpack where by default the creator leaves it disabled, and warns the user that, if they want, they can press F6 to enable First-person

Thaaaats already how it is tho?

> it's not because it doesn't apply to me, I believe that others would also have this problem, and because I believe that it would be better without this feature, with the mod following the last state of First-Person (ON or OFF) when opening, or at least have the possibility to disable the Enabled/Disabled by default feature

You are not asking for this feature to be removed, you are asking for a *separate* button that toggles the option in the settings instead.

**Comment by tr7zw** [comment]
I'll close this tbh. No plans to remove the feature. If anything open a new issue requesting an extra button to toggle the mode and default mode at the same time.
