### ISSUE TITLE
Model disappears when looking forwards.

### ISSUE THREAD

**Issue by Aceplante2** [tr7zw/FirstPersonModel#454]
If I look down at an angle, such as mining a block in the ground, I see my body, but as soon as I am mining a block straight ahead, the model is hidden. This angle seems to be exactly 30 degress:
29.9 degrees:
![30](https://github.com/tr7zw/FirstPersonModel/assets/101857505/84fcac6d-0d7c-48ce-9408-9f74313ecf41)
30 degrees:
![actually30](https://github.com/tr7zw/FirstPersonModel/assets/101857505/6fcb9fa4-0685-48f7-9543-ac0682caa032)

forge 1.17.1

**Comment by AkBaqer** [comment]
i got this issue the same
