### ISSUE TITLE
Playermodel renders twice when in Bed

### ISSUE THREAD

**Issue by AzuryxxVortex** [tr7zw/FirstPersonModel#458]
Minecraft already renders the playermodel when sleeping, and with FPM it adds up to it, leading to two models visible at the same time.
Rather simple issue, that appears to have plagued this mod for a while?

**Comment by tr7zw** [comment]
That is a really good question. Possible that during refactoring some logic got lost.

**Comment by tr7zw** [comment]
Ehhhh I cant see any issue when sleeping? Can you send a pic of the doubled player model?

**Comment by AzuryxxVortex** [comment]
I am unsure of what causes this, but I am using Customizable Player Models with a custom sleep animation, hmm..
![image](https://github.com/tr7zw/FirstPersonModel/assets/112041895/9f1cbcce-987f-4740-9056-59f1bf7ea1ea)
It is quite small and unnoticeable, but there is in fact two arms being rendered- I am unsure how or why..
No additional mods present in the screenshot besides FPM & CPM
