### ISSUE TITLE
Player model head rendering lost when holding a retrieved golem

### ISSUE THREAD

**Issue by jutsumetsu** [tr7zw/FirstPersonModel#460]
Well, this bug occurs when Minecraft is installed with both FPM and Modular Golems.

In first person, neither player nor golem heads are rendered. But in third person, only the golem's head is rendered. As shown below:
![2024-06-14_11 43 27](https://github.com/tr7zw/FirstPersonModel/assets/125746150/b3bea79d-7ba5-4895-a968-afd157545e0e)
![2024-06-14_11 43 39](https://github.com/tr7zw/FirstPersonModel/assets/125746150/a66dc8f7-a719-4968-b766-bfc62ed40408)

Regarding this situation, I have discussed with the developer of Modular Golems. He said that the golem models are all directly called from vanilla entity models. The humanoid golem call the player model, the metal golem call the iron golem model, etc. And when player retrieves the golem, the golem in the inventory will be rendered as an entity.

We guess that the bug occurs like this: When player holds a golem, the golem's entity model is rendered as part of the player's model. And when FPM is enabled, all heads that are considered part of the player model are deleted, and FPM only re-renders the head once in third person. As a result, the golem's head is incorrectly rendered as the player's head, while the real player's head is not rendered.

I suggested to the developer of Modular Golems to add a config file to turn off the entity rendering of the golem in the inventory, and he said he would consider adding it in the next version. However, this is only treating the symptoms and not the root cause. So I came here to report this issue.

**Comment by tr7zw** [comment]
Uhhh of the item renderer renders an entity while the player is rendering, that will trip up the firstperson mod and set head hiding flags incorrectly. Will have to see if I can do anything about this.
