### ISSUE TITLE
The body disappears when swimming fast underwater

### ISSUE THREAD

**Issue by Chocotea92** [tr7zw/FirstPersonModel#462]
https://youtu.be/yEu5M-dfBoU

**Comment by Chocotea92** [comment]
Sorry, version of the mod is firstperson-fabric-2.4.2-mc1.21

**Comment by Vinzound** [comment]
I have the same problem now.

**Comment by tr7zw** [comment]
When you double check everything and still miss 2 lines https://github.com/tr7zw/FirstPersonModel/blob/main/src/main/java/dev/tr7zw/firstperson/mixins/LivingEntityRendererMixin.java#L145 . Gonna do a hotfix tonight.
