### ISSUE TITLE
body disappears when I swim in the water

### ISSUE THREAD

**Issue by masterseafood4568** [tr7zw/FirstPersonModel#463]
FIX THIS NOWWW !!!!!!!!!!!!!!

**Comment by masterseafood4568** [comment]
1.21 please😢

**Comment by Vinzound** [comment]
I have the same problem, I hope it is fixed soon please! :(

**Comment by tr7zw** [comment]
I honestly don't even know how to react to this issue... I really hope for you this was ironic... Duplicate #462
