### ISSUE TITLE
`2.4.3-1.21 - NeoForge` unable to enter Neo `21.0.19-beta` game

### ISSUE THREAD

**Issue by 3gf8jv4dv** [tr7zw/FirstPersonModel#466]
Only the following are installed:
- NeoForge `21.0.19-beta`
- First-person Model `2.4.3-1.21 - NeoForge`

An error message was displayed when entering the game.

<details>
<summary>Preview</summary>

![](https://github.com/tr7zw/FirstPersonModel/assets/158490944/7d618a15-96f1-43f4-8f3b-ddad7a3d79a3)

</details>

Crash log *(Deleted)*

**Comment by tr7zw** [comment]
Known issue, will be fixed in the next next build/release.

**Comment by tr7zw** [comment]
oops there was still an issue open. Yes, that was the point of the 2.4.4 release.
