### ISSUE TITLE
[1.16.4] Can't see underwater

### ISSUE THREAD

**Issue by AuracleTech** [tr7zw/FirstPersonModel#47]
When I swim underwater with xOffset to 10 I see inside my body so I can't see anything.
Maybe a zOffset could fix this. (Also I feel like my eyes are almost inside my neck, maybe zOffset could fix this

**Comment by tr7zw** [comment]
I guess the simpler way would be to not use the xOffset while swimming since it's a different pose anyway (like sneaking).

**Comment by AuracleTech** [comment]
I fixed it by settings xOffset to 12 for now, also I found out that the character rotates too much, it should be more fixed to the camera view and less like F5, that would make the mod almost perfect

**Comment by tr7zw** [comment]
The offsets don't affect swimming anymore, so thin can be closed.
