### ISSUE TITLE
Request Timeless and Classics Zero (TACZ) compat mod

### ISSUE THREAD

**Issue by minhduckd5** [tr7zw/FirstPersonModel#470]
It would be very nice to have it compatible
Basically

- The left arm does not hold the grip
- The ADS animation not working but zoom only
- The reload animation neither working
That would be grateful if it's compatible with TACZ mod, because I wanna see my reloading animation more realistic too (i'm using figura and ysm) (Figura does not work with FPS mod either but I will state the problem later)

**Comment by tr7zw** [comment]
This mod doesn't add 3rd person animations to items etc. That's the job of the mod adding the item.

**Comment by minhduckd5** [comment]
> This mod doesn't add 3rd person animations to items etc. That's the job of the mod adding the item.

I am not asking for 3rd person. I am all saying about the 1st person animation. Aiming down sight and Hand holding grip in TACZ are not right when in 1st person model mod. I do not know who I should report so I just posted on both creators…
Well, since it’s been rejected then fine by me.

**Comment by tr7zw** [comment]
This mod switches to the 3rd person animation. What you see is the same as you see in F5. If there is no animation, that means in F5 there is also no animation, because the mod doesn't have one.
