### ISSUE TITLE
Fabric-1.21 2.4.3 Crossbow Crash

### ISSUE THREAD

**Issue by yuckyh** [tr7zw/FirstPersonModel#471]
Using the crossbow crashes the game in single and multiplayer.

Reverting to 2.4.2 works

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/FirstPersonModel/assets/5133936/ecdebd8b-4e5e-463d-92eb-811e442d9814)
Can't reproduce and no crash log.

**Comment by yuckyh** [comment]
I've found out that the issue was related to another mod that i used which is faster entity animations, after trying to properly reproduce the crash it has nothing to do with this mod. Have a good day 🙏
