### ISSUE TITLE
change z and y offset

### ISSUE THREAD

**Issue by pikuzzo** [tr7zw/FirstPersonModel#475]
why in the mod config there isn't a way to change the z and y camera offset and only the x, i was going to use the real camera mod but then it wont render TAC models.

**Comment by tr7zw** [comment]
Because why would you have the camera come out of your shoulder?

**Comment by pikuzzo** [comment]
> Because why would you have the camera come out of your shoulder?

Bodycam

**Comment by tr7zw** [comment]
Thats not how it would look like. The player would be floating/clip into the floor and into walls when changing the z/y.
