### ISSUE TITLE
1.21 Neo variant crashes when clicking `Config` in the mods list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [tr7zw/FirstPersonModel#484]
[Log](https://gist.github.com/3gf8jv4dv/7f274dcfd663fd56365ce29d516111c1)

**Comment by tr7zw** [comment]
NeoForge apparently made an incompatible change. This will affect all mods and I'll fix that when 1.21.1 releases. For now you can downgrade NeoForge to an older version.
