### ISSUE TITLE
Lack of reflections on held items in first person hands

### ISSUE THREAD

**Issue by tajemniktv** [tr7zw/FirstPersonModel#489]
I think the title explains most of it. I'm pretty sure it's just that it's not a feature in the mod, less of a bug. Unless I'm wrong lol

![image](https://github.com/user-attachments/assets/f48794ee-bbff-460d-9fe6-f5b2fb58c0c8)

![image](https://github.com/user-attachments/assets/5cd7191e-f523-4c81-b1d1-68e5c70ddcb8)

**Comment by tr7zw** [comment]
Never seen a shader that does this, but it's not anything I can do or change.
