### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by VaporeonScripts** [tr7zw/FirstPersonModel#492]
add 1.21.1 support please, ur mod is so cool but cant use on my 1.21.1 modpack!

**Comment by philipgp28** [comment]
one of my favorite qol mods for forge and fabric needs to be updated probably the person is lazy to do it right now

**Comment by VaporeonScripts** [comment]
true

**Comment by JStein01** [comment]
It works if you edit the fabric.mod.json file inside of the jar. Open the archive with 7-zip and then change the minecraft version.

**Comment by john123903** [comment]
> It works if you edit the fabric.mod.json file inside of the jar. Open the archive with 7-zip and then change the minecraft version from 1.21 to 1.21.1. The mod works perfectly for me after I did this.

How??? I didn't find the fabric.mod.json

**Comment by Legendile7** [comment]
> It works if you edit the fabric.mod.json file inside of the jar. Open the archive with 7-zip and then change the minecraft version from 1.21 to 1.21.1. The mod works perfectly for me after I did this.

Thanks so much! For those having trouble, I've attached the file that supports 1.21.1, you just have to change it from .zip to .jar!
[first-person-model.zip](https://github.com/user-attachments/files/17011491/first-person-model.zip)
