### ISSUE TITLE
Maps not working

### ISSUE THREAD

**Issue by Vaqhd** [tr7zw/FirstPersonModel#493]
![2024-08-25_16 52 15](https://github.com/user-attachments/assets/a9075c2e-047e-418b-a07c-4ca185ec3283)

All variants of player maps seem to not be working with this mod, no matter what i do it doesnt actually load a map just the hotbar image. Worked perfectly after turning this mod off so it is definitely the issue. Have i done something wrong or is this a known issue

**Comment by Vaqhd** [comment]
> You are missing the dependency Not Enough Animations.

![2024-08-25_17 59 33](https://github.com/user-attachments/assets/eac1053e-4c79-459e-a01e-d45d00c8315f)
is this how its supposed to look? could fresh animations be incompatible?

**Comment by tr7zw** [comment]
No, not yet sure which mod is incompatible and causing this, but not Fresh Animations.
