### ISSUE TITLE
Request / Question: Enabling rendering of the head

### ISSUE THREAD

**Issue by DoctorVerum** [tr7zw/FirstPersonModel#495]
Just wondering if there is any practical way for me to make the mod to render the head as well? I'm doing some custom player model stuff and want to render elements attached to the head in first person as well, as I'm pretty sure given the design that would be interesting.

You've clearly done a very good job at making the mod not render the head though, because I have so far not succeeded in this. But if anything I'd love the ability to toggle this for alternate player models where the head may not be in the way directly, if that isn't too much work.

**Comment by tr7zw** [comment]
No that is not possible as it won't work. The camera rotates on a fixed spot in space, while the head has its point of rotation at the bottom. That means when you tilt up/down the head, the relative position/rotation of the head/face and camera are all over the place(add onto that stuff like FOV). I think what you are looking for is screen overlays like the pumpkin overlay.
