### ISSUE TITLE
Mod Causes Maps to Flash

### ISSUE THREAD

**Issue by Bvtterbean** [tr7zw/FirstPersonModel#497]
When holding maps in either hand, the map model flashes depending on the angle I'm looking. 

![2024-09-13_19 21 55](https://github.com/user-attachments/assets/3fc7fe3b-65c3-48e6-b668-fc724505c79f)

**Comment by Bvtterbean** [comment]
I've tried it with and without shaders and the problem persists. It is 100% this mod, as it looks just fine when uninstalled.

**Comment by tr7zw** [comment]
Update Not Enough Animations.
