### ISSUE TITLE
A hard-coded name is used instead of the translation key

### ISSUE THREAD

**Issue by Tapacywka** [tr7zw/FirstPersonModel#498]
I'm working on a resourcepack containing translations of settings menus from different mods into other languages (currently US, UA and RU), and I've noticed that instead of a translation key in the mod name, a hard-coded name is used, so I can't interact with it during the translation. Is it possible to output a separate translation key for the mod name in the language file like all other mods do?

![image](https://github.com/user-attachments/assets/c006a4ca-68cb-4aeb-b164-824d34fd86de)

**Comment by tr7zw** [comment]
Dumb question, but how does translating a mod name make sense? Also, it's not hardcoded, that's just the literal translation key ``Firstperson`` https://github.com/tr7zw/FirstPersonModel/blob/5d3b085f96d7a38780cbcf730c73ee2b2160d16f/src/main/java/dev/tr7zw/firstperson/FirstPersonModelCore.java#L19

**Comment by tr7zw** [comment]
Eh, since I'm just finishing up a release so people that updated to 1.21.1 for no reason can stop asking, might as well quickly change that part.
