### ISSUE TITLE
Request: Allow XYZ axis camera adjustments

### ISSUE THREAD

**Issue by rsdadada** [tr7zw/FirstPersonModel#506]
Would it be possible to enable camera adjustments along the Y and Z axes, in addition to the X-axis? I’ve noticed that when using custom player models, the first-person view can feel strange when crouching because the player’s back becomes visible. I think being able to adjust the camera along all three axes could help with this issue and make the perspective feel more natural.

**Comment by tr7zw** [comment]
Camera adjustments are not part of this mod and that's intentional to keep compatibility with mods and servers. You'll need to look for another mod that allows you to do that. The X axes slider in the settings moved the model, not the camera. Crouching btw has its own slider.
