### ISSUE TITLE
Minecraft Crashes on Launch When Using This Mod

### ISSUE THREAD

**Issue by gylertaydos** [tr7zw/FirstPersonModel#507]
Hi all,

I've been using the AT launcher to run Fabric clientside mods for a couple MC versions now, and it's been working great. Today I decided I wanted to install a 3-mod combo to change up my first-person experience. These mods are [First Person Model](https://www.curseforge.com/minecraft/mc-mods/first-person-model), [Not Enough Animations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations), and [Skin Layers 3D](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d). However, each of these three mods causes Minecraft to either crash before even loading the main menu, or (in the case of the last time I attempted to launch) get stuck while loading it. I'll include the three crash reports here (each subsequent report comes after removing the mod mentioned in the error of the previous report, if you understand what I'm saying). I've tried looking through the reports myself but I can't understand what's going wrong. Any help or advise is of course greatly appreciated.

Here is a link to a google drive folder containing the crash reports: https://drive.google.com/drive/folders/1dS8H0V0jVsoPhortf-c1wwl3XgS_uI3s?usp=drive_link

**Comment by tr7zw** [comment]
You are on 1.21.3. There aren't yet 1.21.3 versions of the mods.
