### ISSUE TITLE
Request: Body Rotation Locking

### ISSUE THREAD

**Issue by Matnns** [tr7zw/FirstPersonModel#518]
Hey, I love this mod and I used to play with similar ones in earlier versions of Minecraft too. One feature I wish this mod had was a config option to lock the rotation of the body so that it always matches the camera's yaw. This admittedly looks less natural, but it does make the model less intrusive in instances where you turn your head to look over your shoulder, for example.

**Comment by tr7zw** [comment]
That's in the dependency Not Enough Animations.

**Comment by Matnns** [comment]
Not Enough Animations does this for all animations though, rather than just for the model in first person view. It looks awkward on other players, and the locking is too smooth even on the fixed setting to solve the over the shoulder case I described above. I was thinking something along the lines of what Real First Person did by default IIRC

**Comment by tr7zw** [comment]
There is a setting to not smooth that turning (except for the 1 tick delay I think). Not applying it to other players is a feature request for nea, FirstPerson doesn't modify the player other than hiding parts and offsetting the rendering.

**Comment by Matnns** [comment]
Ah okay! Should I open a request issue for this in NEA? I'm just learning now that you're the owner of both projects.

**Comment by tr7zw** [comment]
Yep open it there so I don't forget about it.
