### ISSUE TITLE
Incompatibility with item Laser Pointer from Web Displays

### ISSUE THREAD

**Issue by Epik0rangutan** [tr7zw/FirstPersonModel#519]
Loader: Latest at time of writing for 1.20.1
Mod Loader: Forge 
![image](https://github.com/user-attachments/assets/65b41fef-42ed-432f-8e39-fdf9c8c7aae7)

**Comment by tr7zw** [comment]
If the mod has no 3rd person animations for the items, you need to add it to the config to auto vanilla hands or the auto mod toggle. This isn't a bug or incompatibility.
