### ISSUE TITLE
Swimming issue / Paper doll suggestion 

### ISSUE THREAD

**Issue by DamienBrittan** [tr7zw/FirstPersonModel#52]
Please , make it possible to move paper doll to top right or bottom right/left . Would be nice :) 
And there's some bugs while swimming in first person at forge version . 
And cosmetics button is , for some reason , top right and (i think) should be at the centre when you press esc (forge version)

**Comment by tr7zw** [comment]
The swimming has been fixed, adding the other 4 corners will be done soon :D

**Comment by tr7zw** [comment]
Actually all of this has is fixed.

**Comment by DamienBrittan** [comment]
yeah , thanks !
