### ISSUE TITLE
Second layer bug (forge)

### ISSUE THREAD

**Issue by DamienBrittan** [tr7zw/FirstPersonModel#54]
When wearing hats or helmets from other mods 
https://pasteboard.co/JGK5oUj.png

**Comment by tr7zw** [comment]
Can you try with the newest build from github?

**Comment by DamienBrittan** [comment]
btw , there's a bug  when you are going out of water you can see your body is too far .

**Comment by tr7zw** [comment]
That's the animation of the player standing up, still something I need to handle differently. Anything with the hat/helmets?

**Comment by DamienBrittan** [comment]
Give me 5 minutes to restart minecraft , when it's 100 mods in it , it's needs some time :D

**Comment by DamienBrittan** [comment]
discord link doesn't work at curgeforge

**Comment by tr7zw** [comment]
It links to https://discord.com/invite/yk4caxM which is the right link?

**Comment by DamienBrittan** [comment]
hats works nice now , thanks for the fix !

**Comment by tr7zw** [comment]
https://tr7zw.dev/u/1609168279.png That invitation is fine and well? https://discord.gg/thTuyWsX this is a newly generated 1-day link, maybe it works better?

**Comment by tr7zw** [comment]
I think this one has been resolved.
