### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by EnderHunter14** [tr7zw/FirstPersonModel#55]
When I load the 1.16.4 fabric/forge version, it won't stop crashing

**Comment by tr7zw** [comment]
Using Fabric or Forge? Did you add the dependencies (Forge: Cloth Config (Forge)) (Fabric: ModMenu, FabricAPI)? Can you post a crash log(Pastebin or so)?

**Comment by tr7zw** [comment]
Closing since I can't do anything with "it's crashing".
