### ISSUE TITLE
Bow is too close

### ISSUE THREAD

**Issue by DamienBrittan** [tr7zw/FirstPersonModel#56]
Forge version 
Bow is too close to my face and cover too much of screen https://imgur.com/a/QJES0ZG

**Comment by tr7zw** [comment]
Technically not a bug, like stated on the Mod page "This mod doesn't change any animations, so you also get to see Mojangs questionable animation decisions(looking at you, shield + bow)." Also the complete abscence of 3rd person eating animations. I think at best I could try to do the same thing I did with the shield, where the body rotation is locked to the head, so the shield appears before your, and not off to the side.

**Comment by ryleu** [comment]
Even though it's technically not a bug, it is a mod-ruining issue that makes it near impossible to use ranged weapons. It also affects the crossbow to some extent, though to a lesser degree.

**Comment by tr7zw** [comment]
That screen doesn't look like the bow is the issue?

**Comment by ryleu** [comment]
This is while the player is in the bow holding animation, looking at an extreme angle upwards, but not straight up. I should still be able to see my surroundings, imo.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/NotEnoughAnimations/actions/runs/4068242699 Made a new test animation for the bow in Not Enough Animations. It's far from perfect, especially due to the required limitations of camera clipping, but it should be a working alternative. Please give this build a try(download is the "Artifacts" button on the page), and then change the "Bow Animation" setting to "Custom V1". I want some feedback on it.
![grafik](https://user-images.githubusercontent.com/5133936/216152252-aabed2cf-a83c-40bf-85ac-03c64f0de454.png)

**Comment by Andre601** [comment]
I personally think that the bow should be one of the few cases where parts of the model should be hidden.
Having to aim while your hand is covering (almost) the entire screen is not fun... And before you say it's only when aiming up, let me ask you a question: Where do you shoot when hitting the ender dragon? I personally aim upwards.

Also, to point it out, here's a screenshot:
![2023-02-06_21 46 40](https://user-images.githubusercontent.com/11576465/217082633-2835901d-56c4-4c0c-8d92-1ba05dcb6f74.png)

**Comment by tr7zw** [comment]
@Andre601 read my comment just above. Currently waiting for any feedback.

**Comment by Andre601** [comment]
> @Andre601 read my comment just above. Currently waiting for any feedback.

Which of the jars is used? The normal, or -all?

**Comment by tr7zw** [comment]
The normal one without any additional part to the name.

**Comment by Andre601** [comment]
You can still see smaller parts of your arms, but it's a lot better than vanilla.

![2023-02-06_21 57 28](https://user-images.githubusercontent.com/11576465/217083967-216d95f6-64b6-4ec2-b67c-d33b7517fe23.png)

**Comment by tr7zw** [comment]
Hm, I wasn't able to see it. Maybe some higher fov?

**Comment by Andre601** [comment]
> Hm, I wasn't able to see it. Maybe some higher fov?

FOV is default (Actually, there isn't even a FOV setting? Using Sodium btw).
The GUI scale is set to auto

**Comment by tr7zw** [comment]
Weird, not then I'll look more into it next time I'm working on the mod.

**Comment by Dr-WeiAL** [comment]
> https://github.com/tr7zw/NotEnoughAnimations/actions/runs/4068242699 Made a new test animation for the bow in Not Enough Animations. It's far from perfect, especially due to the required limitations of camera clipping, but it should be a working alternative. Please give this build a try(download is the "Artifacts" button on the page), and then change the "Bow Animation" setting to "Custom V1". I want some feedback on it. ![grafik](https://user-images.githubusercontent.com/5133936/216152252-aabed2cf-a83c-40bf-85ac-03c64f0de454.png)

Will it only be implemented in 1.19.x? Kind of sad

**Comment by tr7zw** [comment]
Rn don't even know if it will stay. Backports would happen way later.

**Comment by tr7zw** [comment]
I'll call this fine for now. Backported to all versions too.
