### ISSUE TITLE
Tooltips need line breaks

### ISSUE THREAD

**Issue by FewerFlaws** [tr7zw/FirstPersonModel#64]
Read the tooltip first?  How the heck do I do that?  What might get me banned?! =P

![2021-01-06_02 13 33](https://user-images.githubusercontent.com/75643699/103757003-ff479e00-4fc4-11eb-9811-9f238fb3b233.png)

**Comment by tr7zw** [comment]
Yea Minecraft does not take linebreaks in translation keys, and cloth config does not accept multiple translation keys for multiline. I'm fully aware that this string is too large and I'm not sure how to fix it 😅

**Comment by FewerFlaws** [comment]
I think it's like this, but I can't test it:
```
{
    "text.firstperson.option.cosmetic.modifyCameraHeight.@Tooltip[0]": "Changes the first person camera height",
	"text.firstperson.option.cosmetic.modifyCameraHeight.@Tooltip[1]": "to the player size. This will cause issues",
	"text.firstperson.option.cosmetic.modifyCameraHeight.@Tooltip[2]": "with anticheats and might get you banned!",
	"text.firstperson.option.cosmetic.modifyCameraHeight.@Tooltip[3]": "Do not use on 3rd party servers!",
	"text.firstperson.option.cosmetic.modifyCameraHeight.@Tooltip[4]": "(Sneak once to update the height)"
  }
```

**Comment by tr7zw** [comment]
Tried it, doesn't seem to work.

**Comment by RDKRACZ** [comment]
Sorry for duplicating this in #74. Maybe it's a dumb idea but what about two or three tooltips one under the other?

**Comment by FewerFlaws** [comment]
In any case, [here is a function in Bedrockify that wraps lines.](https://github.com/juancarloscp52/BedrockIfy/blob/1.16.2%2B/stable/src/main/java/me/juancarloscp52/bedrockify/client/gui/SettingsGUI.java#L88)  Perhaps a bit more investigation there will reveal the answer.

And [here is another example](https://github.com/HellsingDarge/CompactStatusEffects/blob/master/src/main/resources/assets/compactstatuseffects/lang/en_gb.json#L30) of a mod implementing the pattern I mentioned above.  I'm guessing autoconfig has a linewrapping function and this is how you interact with it.  The example I posted previously probably had its own wrapping going on.
