### ISSUE TITLE
"Cosmetics" button is out of place

### ISSUE THREAD

**Issue by FewerFlaws** [tr7zw/FirstPersonModel#65]
There should be a configuration option to disable the cosmetics button entirely.  Everything there can be accessed through the same mod menu everything else uses.  But I imagine it's only around right now to make testing features easy.

If the button is intended to stay it should be integrated into the existing menu buttons.  I think it'd be great to push the "mods" button to the left and set cosmetics to the right of it.

**Comment by tr7zw** [comment]
Yea the button placement is more temporary, and a workaround for people that don't use mod menu(or don't know about the settings button by modmenu). The correct way would be to better integrate it, but so far I'm not 100% certain where. Maybe a small button like the main menu language/Accessibility buttons? Also I will add a hidden setting in the config to move/remove the button entirely for modpacks mainly.

**Comment by FewerFlaws** [comment]
As someone working on a modpack I appreciate the toggle =D
