### ISSUE TITLE
Broken camera with helmet on.

### ISSUE THREAD

**Issue by RDKRACZ** [tr7zw/FirstPersonModel#67]
![2021-01-07_23 44 42](https://user-images.githubusercontent.com/43277609/103953521-96863000-5142-11eb-8f93-2937f2e4bd4f.png)
![2021-01-07_23 44 45](https://user-images.githubusercontent.com/43277609/103953525-971ec680-5142-11eb-911f-9cb204c30a56.png)

**Comment by tr7zw** [comment]
Which mod is that/what mods are installed and is that the newest build from CurseForge?

**Comment by RDKRACZ** [comment]
I'm using the newest build and this armor is from mythic metals.

**Comment by tr7zw** [comment]
Just tested it and it works. So either not the newest build (2.0.0-alpha6) or some other mod is messing with your player model.

**Comment by RDKRACZ** [comment]
I'm not able to reproduce this which is weird because I didn't remove any mods. Closing for now.

**Comment by tr7zw** [comment]
Reopen when you can reproduce it, my guess is that it was the broken build with optifine that caused that.
