### ISSUE TITLE
Crashes with sit features from Sit and Builders Craft

### ISSUE THREAD

**Issue by ekiplier** [tr7zw/FirstPersonModel#72]
I can't use the sit features added by other mods with this mod installed.

I will upload the crash report and logs file

[latest.log](https://github.com/tr7zw/FirstPersonModel/files/5798944/latest.log)

[crash-2021-01-11_23.37.55-client.txt](https://github.com/tr7zw/FirstPersonModel/files/5798947/crash-2021-01-11_23.37.55-client.txt)

**Comment by tr7zw** [comment]
It appears that it replaces the player entity with a non-Living Entity to simulate the sitting. Not sure if that forge mod will ever be compatible since that's really not-standard behavior(and will probably create issues with a lot of other mods?). Can you link the 2 mods?

**Comment by Water-Moon** [comment]
I don't know if it's still valid to mention it here (since the error is fixed), but actually, the current version will crash if you sit on anything other than an entity that extends LivingEntity (this includes minecart......)

**Comment by tr7zw** [comment]
That's exactly what that commit fixed, it's just not yet on cf. You can download the build from the Actions tab above to test it.
