### ISSUE TITLE
getting into a boat or minecart on the 1.16.4 forge snapshot crashes the game

### ISSUE THREAD

**Issue by tobymaxgames** [tr7zw/FirstPersonModel#73]
title basically describes the whole issue. 
having you body visible while in a minecart/boat causes the game to crash. **only** happen when you have your body visible, sitting in a vehicle with the mod features **disabled** causes no crash up until you enable it.

mod version is FirstPersonMod-2.0.0-SNAPSHOT
forge version is forge-35.1.4

**Comment by tr7zw** [comment]
Please try https://github.com/tr7zw/FirstPersonModel/actions/runs/481091173

**Comment by tobymaxgames** [comment]
wow that was insanely fast, that fixed it, thanks!

**Comment by tr7zw** [comment]
Yea I'll try to put that version on CurseForge tomorrow :)
