### ISSUE TITLE
Crash with better hurt timer mod

### ISSUE THREAD

**Issue by Spoofygamer** [tr7zw/FirstPersonModel#78]
[crash-2021-01-19_16.47.37-client.txt](https://github.com/tr7zw/FirstPersonModel/files/5838785/crash-2021-01-19_16.47.37-client.txt)

**Comment by NovaN4** [comment]
I'm not having this crash, and I have both mods paired with each other. I believe this crash was a common occurrence on older versions of Better Hurt Timer, try getting the most recent version of that mod.

**Comment by tr7zw** [comment]
Yea there was an issue that when you had a certain combination of mods it caused an error. But its fixed now.
