### ISSUE TITLE
Forge Entity shadows

### ISSUE THREAD

**Issue by Litttlefish** [tr7zw/FirstPersonModel#94]
3D layer effect and cosmetics does nothing
And entity shadows won't show below other entities
My version using now is 2.0 beta1

**Comment by tr7zw** [comment]
3D layer is not yet implemented for the Forge version.
And yea with the entity shadows I'll have to look into it(not sure if the Fabric version has that issue?), but probably a problem with the the shadow offsets.

**Comment by tr7zw** [comment]
Ok, I actually did accidentally cancel the shadow rendering for anything but the main player. Fixed in the next release.
