### ISSUE TITLE
Paperdoll animation is different when flying with the elytra

### ISSUE THREAD

**Issue by NetflixGutschein** [tr7zw/FirstPersonModel#96]
If I start flying with my elytra, the players legs shake (they have the "running" animation) after a few seconds of flying, my legs stop moving. But the paper doll is still showing the animation with moving legs. In the inventory it is also correctly shown (and upside down, but thats a minecraft problem)

https://i.imgur.com/Rtjaqoe.png
https://i.imgur.com/jh9z1BL.png

**Comment by tr7zw** [comment]
This is fixed in the Paperdoll mod I think.
