### ISSUE TITLE
"I can see my diamond helmet issue" is still an issue unfortunately.

### ISSUE THREAD

**Issue by zndrmn** [tr7zw/FirstPersonModel#98]
I think the problem could be because of a mod incapability

**Comment by tr7zw** [comment]
It *is* because of a mod incomparability.
Forge/Fabric?
Using 2.0.0 beta2?
Which other mods are installed?

**Comment by SoldierGoggles51** [comment]
The problem I have is with obfuscate-0.6.0-mc1.16.4.jar

Modloader: Forge
Version: 2.0.0 beta2

**Comment by zndrmn** [comment]
Oh did you get it down to obfuscate or? Cause I removed that mod yesterday while I was moving my files to a new directory.

Also sorry I haven't had the time to test all of the mods I listed.

**Comment by SoldierGoggles51** [comment]
Yep i did and yes I was using cgm
Hope this helps

**Comment by tr7zw** [comment]
https://www.curseforge.com/minecraft/mc-mods/obfuscate I imagine? Sounds likely that it could do something odd that does cause this behavior. I'll look into how to make it compatible.

**Comment by zndrmn** [comment]
In 20 min I can test to see if I have the issue still cause I removed both obfuscate and cgm last night and I didn't really play after the fact so.

**Comment by SoldierGoggles51** [comment]
> https://www.curseforge.com/minecraft/mc-mods/obfuscate I imagine? Sounds likely that it could do something odd that does cause this behavior. I'll look into how to make it compatible.

Yep that's it right there
And I hope you can make it compatible

**Comment by zndrmn** [comment]
Also regarding cgm which requires obfuscate, do you think you will be able to add compatibility with it. It seems that it would be tough to do because it uses custom gun models and all that.

**Comment by tr7zw** [comment]
Everything that works in 3rd person should work with this mod. Afaik some weapon mods have an issue that it renders the 3rd person arm+weapon and the first person arm with the gun.

**Comment by zndrmn** [comment]
Here's the link to the mod
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod

**Comment by SoldierGoggles51** [comment]
That was one of the issues I've but I pretty much fixed it by disabling the first person mod

**Comment by tr7zw** [comment]
Yea there should be an issue made on the gun mod that if the hand item is canceled, then don't render your item in hand xD This probably also causes issues with other mods that just want to hide the first-person arms for a moment.

**Comment by SoldierGoggles51** [comment]
Yeah XD

**Comment by zndrmn** [comment]
Yep, I just tested it with obfuscate. 100% was the problem.

**Comment by tr7zw** [comment]
Fixed the helmet issue with obfuscate, but the other issues remain for now (Paperdoll not liking to hold a weapon/2 sets of arms when holding a gun), but at least it's no permanent "helmet in the face" issue anymore.

**Comment by tr7zw** [comment]
Ok got the second pair of arms fixed too.
