### ISSUE TITLE
Potential incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by muzikbike** [tr7zw/FirstPersonModel#99]
With firstpersonmodel and the six other dependencies linked in both the relations tab and in the main text, the player model renders just fine:
![2021-02-26_21 43 00](https://user-images.githubusercontent.com/52297970/109358724-1e073a00-787c-11eb-96d1-c0fd1f3d14d6.png)

Throw Immersive Portals into the mix, and bye player model:
![2021-02-26_21 45 07](https://user-images.githubusercontent.com/52297970/109358748-28293880-787c-11eb-9d2e-d91730ff5748.png)
![2021-02-26_21 47 13](https://user-images.githubusercontent.com/52297970/109358788-3c6d3580-787c-11eb-8c37-8f2e173580cf.png)

**Comment by tr7zw** [comment]
That is odd, I guess immersive portals somehow has special logic to make the travel of entities seamless, which is now breaking? I'll look into it.

**Comment by tr7zw** [comment]
Doesn't seem to be an issue anymore, just issues with tilted portals #355
